import { CardType } from '../database/types';

export interface LessonCard {
  type: CardType;
  value: string;
}

interface Lesson {
  id: number;
  title: string;
  cards: LessonCard[];
}

interface Course {
  id: number;
  title: string;
  lessons: Lesson[];
}

export const courses: Course[] = [
  {
    id: 3,
    title: 'Most frequent words',
    lessons: [
      {
        id: 1,
        title: 'Lesson 1',
        cards: [
          { type: CardType.VERB, value: 'sein' },
          { type: CardType.VERB, value: 'haben' },
          { type: CardType.VERB, value: 'werden' },
          { type: CardType.NOUN, value: 'Jahr' },
          { type: CardType.NOUN, value: 'Mal' },
          { type: CardType.NOUN, value: 'Beispiel' },
          { type: CardType.ADJECTIVE, value: 'ganz' },
          { type: CardType.ADJECTIVE, value: 'groß' },
          { type: CardType.ADJECTIVE, value: 'gut' },
        ],
      },
      {
        id: 2,
        title: 'Lesson 2',
        cards: [
          { type: CardType.NOUN, value: 'Zeit' },
          { type: CardType.NOUN, value: 'Frau' },
          { type: CardType.NOUN, value: 'Mensch' },
          { type: CardType.ADJECTIVE, value: 'neu' },
          { type: CardType.ADJECTIVE, value: 'erste' },
          { type: CardType.ADJECTIVE, value: 'lang' },
          { type: CardType.VERB, value: 'können' },
          { type: CardType.VERB, value: 'müssen' },
          { type: CardType.VERB, value: 'sagen' },
        ],
      },
      {
        id: 3,
        title: 'Lesson 3',
        cards: [
          { type: CardType.ADJECTIVE, value: 'klein' },
          { type: CardType.ADJECTIVE, value: 'alt' },
          { type: CardType.ADJECTIVE, value: 'deutsch' },
          { type: CardType.VERB, value: 'machen' },
          { type: CardType.VERB, value: 'geben' },
          { type: CardType.VERB, value: 'kommen' },
          { type: CardType.NOUN, value: 'Deutsch' },
          { type: CardType.NOUN, value: 'Kind' },
          { type: CardType.NOUN, value: 'Tag' },
        ],
      },
      {
        id: 4,
        title: 'Lesson 4',
        cards: [
          { type: CardType.VERB, value: 'sollen' },
          { type: CardType.VERB, value: 'wollen' },
          { type: CardType.VERB, value: 'gehen' },
          { type: CardType.NOUN, value: 'Mann' },
          { type: CardType.NOUN, value: 'Land' },
          { type: CardType.NOUN, value: 'Frage' },
          { type: CardType.ADJECTIVE, value: 'hoch' },
          { type: CardType.ADJECTIVE, value: 'einfach' },
          { type: CardType.ADJECTIVE, value: 'letzte' },
        ],
      },
      {
        id: 5,
        title: 'Lesson 5',
        cards: [
          { type: CardType.VERB, value: 'wissen' },
          { type: CardType.VERB, value: 'sehen' },
          { type: CardType.VERB, value: 'lassen' },
          { type: CardType.NOUN, value: 'Haus' },
          { type: CardType.NOUN, value: 'Fall' },
          { type: CardType.NOUN, value: 'Leute' },
          { type: CardType.ADJECTIVE, value: 'gleich' },
          { type: CardType.ADJECTIVE, value: 'möglich' },
          { type: CardType.ADJECTIVE, value: 'eigen' },
        ],
      },
      {
        id: 6,
        title: 'Lesson 6',
        cards: [
          { type: CardType.VERB, value: 'stehen' },
          { type: CardType.VERB, value: 'finden' },
          { type: CardType.VERB, value: 'bleiben' },
          { type: CardType.NOUN, value: 'Arbeit' },
          { type: CardType.NOUN, value: 'Prozent' },
          { type: CardType.NOUN, value: 'Hand' },
          { type: CardType.ADJECTIVE, value: 'schön' },
          { type: CardType.ADJECTIVE, value: 'spät' },
          { type: CardType.ADJECTIVE, value: 'wichtig' },
        ],
      },
      {
        id: 7,
        title: 'Lesson 7',
        cards: [
          { type: CardType.VERB, value: 'liegen' },
          { type: CardType.VERB, value: 'heißen' },
          { type: CardType.VERB, value: 'denken' },
          { type: CardType.NOUN, value: 'Stadt' },
          { type: CardType.NOUN, value: 'Herr' },
          { type: CardType.NOUN, value: 'Teil' },
          { type: CardType.ADJECTIVE, value: 'weitere' },
          { type: CardType.ADJECTIVE, value: 'genau' },
          { type: CardType.ADJECTIVE, value: 'jung' },
        ],
      },
      {
        id: 8,
        title: 'Lesson 8',
        cards: [
          { type: CardType.VERB, value: 'nehmen' },
          { type: CardType.VERB, value: 'tun' },
          { type: CardType.VERB, value: 'dürfen' },
          { type: CardType.NOUN, value: 'Problem' },
          { type: CardType.NOUN, value: 'Welt' },
          { type: CardType.NOUN, value: 'Recht' },
          { type: CardType.ADJECTIVE, value: 'kurz' },
          { type: CardType.ADJECTIVE, value: 'stark' },
          { type: CardType.ADJECTIVE, value: 'richtig' },
        ],
      },
      {
        id: 9,
        title: 'Lesson 9',
        cards: [
          { type: CardType.VERB, value: 'glauben' },
          { type: CardType.VERB, value: 'halten' },
          { type: CardType.VERB, value: 'nennen' },
          { type: CardType.NOUN, value: 'Ende' },
          { type: CardType.NOUN, value: 'Million' },
          { type: CardType.NOUN, value: 'Schule' },
          { type: CardType.ADJECTIVE, value: 'verschieden' },
          { type: CardType.ADJECTIVE, value: 'bestimmt' },
          { type: CardType.ADJECTIVE, value: 'besser' },
        ],
      },
      {
        id: 10,
        title: 'Lesson 10',
        cards: [
          { type: CardType.VERB, value: 'mögen' },
          { type: CardType.VERB, value: 'zeigen' },
          { type: CardType.VERB, value: 'führen' },
          { type: CardType.NOUN, value: 'Woche' },
          { type: CardType.NOUN, value: 'Vater' },
          { type: CardType.NOUN, value: 'Seite' },
          { type: CardType.ADJECTIVE, value: 'schnell' },
          { type: CardType.ADJECTIVE, value: 'sicher' },
          { type: CardType.ADJECTIVE, value: 'nächste' },
        ],
      },
      {
        id: 11,
        title: 'Lesson 11',
        cards: [
          { type: CardType.VERB, value: 'sprechen' },
          { type: CardType.VERB, value: 'bringen' },
          { type: CardType.VERB, value: 'leben' },
          { type: CardType.NOUN, value: 'Leben' },
          { type: CardType.NOUN, value: 'Mutter' },
          { type: CardType.NOUN, value: 'Grund' },
          { type: CardType.ADJECTIVE, value: 'politisch' },
          { type: CardType.ADJECTIVE, value: 'klar' },
          { type: CardType.ADJECTIVE, value: 'schwer' },
        ],
      },
      {
        id: 12,
        title: 'Lesson 12',
        cards: [
          { type: CardType.VERB, value: 'fahren' },
          { type: CardType.VERB, value: 'meinen' },
          { type: CardType.VERB, value: 'fragen' },
          { type: CardType.NOUN, value: 'Auge' },
          { type: CardType.NOUN, value: 'Wort' },
          { type: CardType.NOUN, value: 'Geld' },
          { type: CardType.ADJECTIVE, value: 'einzeln' },
          { type: CardType.ADJECTIVE, value: 'bekannt' },
          { type: CardType.ADJECTIVE, value: 'leicht' },
        ],
      },
      {
        id: 13,
        title: 'Lesson 13',
        cards: [
          { type: CardType.VERB, value: 'kennen' },
          { type: CardType.VERB, value: 'gelten' },
          { type: CardType.VERB, value: 'stellen' },
          { type: CardType.NOUN, value: 'Art' },
          { type: CardType.NOUN, value: 'Bereich' },
          { type: CardType.NOUN, value: 'Weg' },
          { type: CardType.ADJECTIVE, value: 'rund' },
          { type: CardType.ADJECTIVE, value: 'frei' },
          { type: CardType.ADJECTIVE, value: 'früh' },
        ],
      },
      {
        id: 14,
        title: 'Lesson 14',
        cards: [
          { type: CardType.VERB, value: 'spielen' },
          { type: CardType.VERB, value: 'arbeiten' },
          { type: CardType.VERB, value: 'brauchen' },
          { type: CardType.NOUN, value: 'Stunde' },
          { type: CardType.NOUN, value: 'Name' },
          { type: CardType.NOUN, value: 'Geschichte' },
          { type: CardType.ADJECTIVE, value: 'unterschiedlich' },
          { type: CardType.ADJECTIVE, value: 'schlecht' },
          { type: CardType.ADJECTIVE, value: 'deutlich' },
        ],
      },
      {
        id: 15,
        title: 'Lesson 15',
        cards: [
          { type: CardType.VERB, value: 'folgen' },
          { type: CardType.VERB, value: 'lernen' },
          { type: CardType.VERB, value: 'bestehen' },
          { type: CardType.NOUN, value: 'Gesellschaft' },
          { type: CardType.NOUN, value: 'Kopf' },
          { type: CardType.NOUN, value: 'Paar' },
          { type: CardType.ADJECTIVE, value: 'allgemein' },
          { type: CardType.ADJECTIVE, value: 'einzig' },
          { type: CardType.ADJECTIVE, value: 'gemeinsam' },
        ],
      },
      {
        id: 16,
        title: 'Lesson 16',
        cards: [
          { type: CardType.VERB, value: 'verstehen' },
          { type: CardType.VERB, value: 'setzen' },
          { type: CardType.VERB, value: 'bekommen' },
          { type: CardType.NOUN, value: 'Möglichkeit' },
          { type: CardType.NOUN, value: 'Unternehmen' },
          { type: CardType.NOUN, value: 'Bild' },
          { type: CardType.ADJECTIVE, value: 'nahe' },
          { type: CardType.ADJECTIVE, value: 'voll' },
          { type: CardType.ADJECTIVE, value: 'direkt' },
        ],
      },
      {
        id: 17,
        title: 'Lesson 17',
        cards: [
          { type: CardType.VERB, value: 'beginnen' },
          { type: CardType.VERB, value: 'erzählen' },
          { type: CardType.VERB, value: 'versuchen' },
          { type: CardType.NOUN, value: 'Buch' },
          { type: CardType.NOUN, value: 'Wasser' },
          { type: CardType.NOUN, value: 'Stelle' },
          { type: CardType.ADJECTIVE, value: 'international' },
          { type: CardType.ADJECTIVE, value: 'sozial' },
          { type: CardType.ADJECTIVE, value: 'beste' },
        ],
      },
      {
        id: 18,
        title: 'Lesson 18',
        cards: [
          { type: CardType.VERB, value: 'schreiben' },
          { type: CardType.VERB, value: 'laufen' },
          { type: CardType.VERB, value: 'erklären' },
          { type: CardType.NOUN, value: 'Form' },
          { type: CardType.NOUN, value: 'Entwicklung' },
          { type: CardType.NOUN, value: 'Monat' },
          { type: CardType.ADJECTIVE, value: 'rot' },
          { type: CardType.ADJECTIVE, value: 'offen' },
          { type: CardType.ADJECTIVE, value: 'meiste' },
        ],
      },
      {
        id: 19,
        title: 'Lesson 19',
        cards: [
          { type: CardType.VERB, value: 'entsprechen' },
          { type: CardType.VERB, value: 'sitzen' },
          { type: CardType.VERB, value: 'ziehen' },
          { type: CardType.NOUN, value: 'Familie' },
          { type: CardType.NOUN, value: 'Morgen' },
          { type: CardType.NOUN, value: 'Abend' },
          { type: CardType.ADJECTIVE, value: 'besondere' },
          { type: CardType.ADJECTIVE, value: 'gewiss' },
          { type: CardType.ADJECTIVE, value: 'öffentlich' },
        ],
      },
      {
        id: 20,
        title: 'Lesson 20',
        cards: [
          { type: CardType.VERB, value: 'scheinen' },
          { type: CardType.VERB, value: 'fallen' },
          { type: CardType.VERB, value: 'gehören' },
          { type: CardType.NOUN, value: 'Aufgabe' },
          { type: CardType.NOUN, value: 'Universität' },
          { type: CardType.NOUN, value: 'Sinn' },
          { type: CardType.ADJECTIVE, value: 'halb' },
          { type: CardType.ADJECTIVE, value: 'wahrscheinlich' },
          { type: CardType.ADJECTIVE, value: 'europäisch' },
        ],
      },
      {
        id: 21,
        title: 'Lesson 21',
        cards: [
          { type: CardType.VERB, value: 'entstehen' },
          { type: CardType.VERB, value: 'erhalten' },
          { type: CardType.VERB, value: 'treffen' },
          { type: CardType.NOUN, value: 'Staat' },
          { type: CardType.NOUN, value: 'Ziel' },
          { type: CardType.NOUN, value: 'Freund' },
          { type: CardType.ADJECTIVE, value: 'wesentlich' },
          { type: CardType.ADJECTIVE, value: 'ähnlich' },
          { type: CardType.ADJECTIVE, value: 'häufig' },
        ],
      },
      {
        id: 22,
        title: 'Lesson 22',
        cards: [
          { type: CardType.VERB, value: 'suchen' },
          { type: CardType.VERB, value: 'legen' },
          { type: CardType.VERB, value: 'vorstellen' },
          { type: CardType.NOUN, value: 'Thema' },
          { type: CardType.NOUN, value: 'Person' },
          { type: CardType.NOUN, value: 'Euro' },
          { type: CardType.ADJECTIVE, value: 'schwarz' },
          { type: CardType.ADJECTIVE, value: 'völlig' },
          { type: CardType.ADJECTIVE, value: 'gering' },
        ],
      },
      {
        id: 23,
        title: 'Lesson 23',
        cards: [
          { type: CardType.VERB, value: 'handeln' },
          { type: CardType.VERB, value: 'erreichen' },
          { type: CardType.VERB, value: 'tragen' },
          { type: CardType.NOUN, value: 'Nacht' },
          { type: CardType.NOUN, value: 'Ding' },
          { type: CardType.NOUN, value: 'Raum' },
          { type: CardType.ADJECTIVE, value: 'schwierig' },
          { type: CardType.ADJECTIVE, value: 'praktisch' },
          { type: CardType.ADJECTIVE, value: 'persönlich' },
        ],
      },
      {
        id: 24,
        title: 'Lesson 24',
        cards: [
          { type: CardType.VERB, value: 'schaffen' },
          { type: CardType.VERB, value: 'lesen' },
          { type: CardType.VERB, value: 'verlieren' },
          { type: CardType.NOUN, value: 'Blick' },
          { type: CardType.NOUN, value: 'Platz' },
          { type: CardType.NOUN, value: 'Zahl' },
          { type: CardType.ADJECTIVE, value: '–jährig' },
          { type: CardType.ADJECTIVE, value: 'modern' },
          { type: CardType.ADJECTIVE, value: 'tief' },
        ],
      },
      {
        id: 25,
        title: 'Lesson 25',
        cards: [
          { type: CardType.VERB, value: 'darstellen' },
          { type: CardType.VERB, value: 'erkennen' },
          { type: CardType.VERB, value: 'entwickeln' },
          { type: CardType.NOUN, value: 'System' },
          { type: CardType.NOUN, value: 'Uhr' },
          { type: CardType.NOUN, value: 'Eltern' },
          { type: CardType.ADJECTIVE, value: 'tatsächlich' },
          { type: CardType.ADJECTIVE, value: 'zusätzlich' },
          { type: CardType.ADJECTIVE, value: 'wirtschaftlich' },
        ],
      },
      {
        id: 26,
        title: 'Lesson 26',
        cards: [
          { type: CardType.VERB, value: 'reden' },
          { type: CardType.VERB, value: 'aussehen' },
          { type: CardType.VERB, value: 'erscheinen' },
          { type: CardType.NOUN, value: 'Straße' },
          { type: CardType.NOUN, value: 'Minute' },
          { type: CardType.NOUN, value: 'Gruppe' },
          { type: CardType.ADJECTIVE, value: 'interessant' },
          { type: CardType.ADJECTIVE, value: 'relativ' },
          { type: CardType.ADJECTIVE, value: 'gleichzeitig' },
        ],
      },
      {
        id: 27,
        title: 'Lesson 27',
        cards: [
          { type: CardType.VERB, value: 'bilden' },
          { type: CardType.VERB, value: 'anfangen' },
          { type: CardType.VERB, value: 'erwarten' },
          { type: CardType.NOUN, value: 'Wert' },
          { type: CardType.NOUN, value: 'Gesicht' },
          { type: CardType.NOUN, value: 'Sprache' },
          { type: CardType.ADJECTIVE, value: 'grün' },
          { type: CardType.ADJECTIVE, value: 'weiß' },
          { type: CardType.ADJECTIVE, value: 'gesamt' },
        ],
      },
      {
        id: 28,
        title: 'Lesson 28',
        cards: [
          { type: CardType.VERB, value: 'wohnen' },
          { type: CardType.VERB, value: 'betreffen' },
          { type: CardType.VERB, value: 'warten' },
          { type: CardType.NOUN, value: 'Anfang' },
          { type: CardType.NOUN, value: 'Ort' },
          { type: CardType.NOUN, value: 'Moment' },
          { type: CardType.ADJECTIVE, value: 'speziell' },
          { type: CardType.ADJECTIVE, value: 'entscheidend' },
          { type: CardType.ADJECTIVE, value: 'eng' },
        ],
      },
      {
        id: 29,
        title: 'Lesson 29',
        cards: [
          { type: CardType.VERB, value: 'vergehen' },
          { type: CardType.VERB, value: 'helfen' },
          { type: CardType.VERB, value: 'gewinnen' },
          { type: CardType.NOUN, value: 'Folge' },
          { type: CardType.NOUN, value: 'Interesse' },
          { type: CardType.NOUN, value: 'Milliarde' },
          { type: CardType.ADJECTIVE, value: 'technisch' },
          { type: CardType.ADJECTIVE, value: 'langsam' },
          { type: CardType.ADJECTIVE, value: 'ständig' },
        ],
      },
      {
        id: 30,
        title: 'Lesson 30',
        cards: [
          { type: CardType.VERB, value: 'schließen' },
          { type: CardType.VERB, value: 'fühlen' },
          { type: CardType.VERB, value: 'bieten' },
          { type: CardType.NOUN, value: 'Rolle' },
          { type: CardType.NOUN, value: 'Tür' },
          { type: CardType.NOUN, value: 'Schüler' },
          { type: CardType.ADJECTIVE, value: 'notwendig' },
          { type: CardType.ADJECTIVE, value: 'rein' },
          { type: CardType.ADJECTIVE, value: 'englisch' },
        ],
      },
      {
        id: 31,
        title: 'Lesson 31',
        cards: [
          { type: CardType.VERB, value: 'interessieren' },
          { type: CardType.VERB, value: 'erinnern' },
          { type: CardType.VERB, value: 'ergeben' },
          { type: CardType.NOUN, value: 'Bedeutung' },
          { type: CardType.NOUN, value: 'Text' },
          { type: CardType.NOUN, value: 'Ergebnis' },
          { type: CardType.ADJECTIVE, value: 'wissenschaftlich' },
          { type: CardType.ADJECTIVE, value: 'falsch' },
          { type: CardType.ADJECTIVE, value: 'fremd' },
        ],
      },
      {
        id: 32,
        title: 'Lesson 32',
        cards: [
          { type: CardType.VERB, value: 'anbieten' },
          { type: CardType.VERB, value: 'studieren' },
          { type: CardType.VERB, value: 'verbinden' },
          { type: CardType.NOUN, value: 'Krieg' },
          { type: CardType.NOUN, value: 'Weise' },
          { type: CardType.NOUN, value: 'Regierung' },
          { type: CardType.ADJECTIVE, value: 'selten' },
          { type: CardType.ADJECTIVE, value: 'normal' },
          { type: CardType.ADJECTIVE, value: 'wahr' },
        ],
      },
      {
        id: 33,
        title: 'Lesson 33',
        cards: [
          { type: CardType.VERB, value: 'ansehen' },
          { type: CardType.VERB, value: 'fehlen' },
          { type: CardType.VERB, value: 'bedeuten' },
          { type: CardType.NOUN, value: 'Stück' },
          { type: CardType.NOUN, value: 'Wohnung' },
          { type: CardType.NOUN, value: 'Gespräch' },
          { type: CardType.ADJECTIVE, value: 'privat' },
          { type: CardType.ADJECTIVE, value: 'tot' },
          { type: CardType.ADJECTIVE, value: 'fest' },
        ],
      },
      {
        id: 34,
        title: 'Lesson 34',
        cards: [
          { type: CardType.VERB, value: 'vergleichen' },
          { type: CardType.VERB, value: 'steigen' },
          { type: CardType.VERB, value: 'nutzen' },
          { type: CardType.NOUN, value: 'Meter' },
          { type: CardType.ADJECTIVE, value: 'positiv' },
          { type: CardType.ADJECTIVE, value: 'zentral' },
          { type: CardType.ADJECTIVE, value: 'fertig' },
        ],
      },
    ],
  },
  {
    id: 1,
    title: 'My German',
    lessons: [
      {
        id: 1,
        title: 'Articles',
        cards: [
          {
            type: CardType.ARTICLE,
            value: 'der',
          },
          {
            type: CardType.ARTICLE,
            value: 'dieF',
          },
          {
            type: CardType.ARTICLE,
            value: 'das',
          },
          {
            type: CardType.ARTICLE,
            value: 'dieP',
          },
          {
            type: CardType.ARTICLE,
            value: 'einM',
          },
          {
            type: CardType.ARTICLE,
            value: 'eine',
          },
          {
            type: CardType.ARTICLE,
            value: 'einN',
          },
        ],
      },
    ],
  },
  {
    id: 4,
    title: 'LingQ lessons',
    lessons: [
      {
        id: 1,
        title: '1',
        cards: [
          { type: CardType.NOUN, value: 'Gut' },
          { type: CardType.VERB, value: 'sein' },
          { type: CardType.ADJECTIVE, value: 'neu' },
          { type: CardType.ADJECTIVE, value: 'echt' },
          { type: CardType.NOUN, value: 'Ahnung' },
          { type: CardType.VERB, value: 'haben' },
          { type: CardType.VERB, value: 'vergessen' },
          { type: CardType.VERB, value: 'tun' },
          { type: CardType.NOUN, value: 'Problem' },
          { type: CardType.NOUN, value: 'Entschuldigung' },
          { type: CardType.ADJECTIVE, value: 'fremd' },
          { type: CardType.VERB, value: 'glauben' },
          { type: CardType.NOUN, value: 'Ende' },
          { type: CardType.NOUN, value: 'Bitte' },
          { type: CardType.VERB, value: 'müssen' },
          { type: CardType.VERB, value: 'gehen' },
          { type: CardType.NOUN, value: 'Glück' },
          { type: CardType.VERB, value: 'lieben' },
          { type: CardType.NOUN, value: 'Zukunft' },
          { type: CardType.VERB, value: 'klingen' },
          { type: CardType.ADJECTIVE, value: 'gut' },
        ],
      },
    ],
  },
];
