import { CardType } from '../database/types';
// import { chunkArray, shuffleArrayByType } from '../utils/array';

export interface LessonCard {
  type: CardType;
  value: string;
  hidden?: boolean;
}

export interface Lesson {
  id: number;
  title: string;
  cards: LessonCard[];
}

export interface Course {
  id: number;
  title: string;
  lessons: Lesson[];
}

export const courses: Course[] = [
  {
    id: 3,
    title: 'Most frequent words',
    lessons: [
      {
        id: 1,
        title: 'Lesson 1',
        cards: [
          { type: CardType.VERB, value: 'sein' },
          { type: CardType.VERB, value: 'haben' },
          { type: CardType.VERB, value: 'werden' },
          { type: CardType.NOUN, value: 'Jahr' },
          { type: CardType.NOUN, value: 'Mal' },
          { type: CardType.NOUN, value: 'Beispiel' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'ganz' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'groß' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'gut' },
        ],
      },
      {
        id: 2,
        title: 'Lesson 2',
        cards: [
          { type: CardType.NOUN, value: 'Zeit' },
          { type: CardType.NOUN, value: 'Frau' },
          { type: CardType.NOUN, value: 'Mensch' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'neu' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'erste' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'lang' },
          { type: CardType.VERB, value: 'können' },
          { type: CardType.VERB, value: 'müssen' },
          { type: CardType.VERB, value: 'sagen' },
        ],
      },
      {
        id: 3,
        title: 'Lesson 3',
        cards: [
          { type: CardType.ADJECTIVE_ADVERB, value: 'klein' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'alt' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'deutsch' },
          { type: CardType.VERB, value: 'machen' },
          { type: CardType.VERB, value: 'geben' },
          { type: CardType.VERB, value: 'kommen' },
          { type: CardType.NOUN, value: 'Deutsch' },
          { type: CardType.NOUN, value: 'Kind' },
          { type: CardType.NOUN, value: 'Tag' },
        ],
      },
      {
        id: 4,
        title: 'Lesson 4',
        cards: [
          { type: CardType.VERB, value: 'sollen' },
          { type: CardType.VERB, value: 'wollen' },
          { type: CardType.VERB, value: 'gehen' },
          { type: CardType.NOUN, value: 'Mann' },
          { type: CardType.NOUN, value: 'Land' },
          { type: CardType.NOUN, value: 'Frage' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'hoch' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'einfach' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'letzte' },
        ],
      },
      {
        id: 5,
        title: 'Lesson 5',
        cards: [
          { type: CardType.VERB, value: 'wissen' },
          { type: CardType.VERB, value: 'sehen' },
          { type: CardType.VERB, value: 'lassen' },
          { type: CardType.NOUN, value: 'Haus' },
          { type: CardType.NOUN, value: 'Fall' },
          { type: CardType.NOUN, value: 'Leute' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'gleich' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'möglich' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'eigen' },
        ],
      },
      {
        id: 6,
        title: 'Lesson 6',
        cards: [
          { type: CardType.VERB, value: 'stehen' },
          { type: CardType.VERB, value: 'finden' },
          { type: CardType.VERB, value: 'bleiben' },
          { type: CardType.NOUN, value: 'Arbeit' },
          { type: CardType.NOUN, value: 'Prozent' },
          { type: CardType.NOUN, value: 'Hand' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'schön' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'spät' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'wichtig' },
        ],
      },
      {
        id: 7,
        title: 'Lesson 7',
        cards: [
          { type: CardType.VERB, value: 'liegen' },
          { type: CardType.VERB, value: 'heißen' },
          { type: CardType.VERB, value: 'denken' },
          { type: CardType.NOUN, value: 'Stadt' },
          { type: CardType.NOUN, value: 'Herr' },
          { type: CardType.NOUN, value: 'Teil' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'weitere' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'genau' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'jung' },
        ],
      },
      {
        id: 8,
        title: 'Lesson 8',
        cards: [
          { type: CardType.VERB, value: 'nehmen' },
          { type: CardType.VERB, value: 'tun' },
          { type: CardType.VERB, value: 'dürfen' },
          { type: CardType.NOUN, value: 'Problem' },
          { type: CardType.NOUN, value: 'Welt' },
          { type: CardType.NOUN, value: 'Recht' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'kurz' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'stark' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'richtig' },
        ],
      },
      {
        id: 9,
        title: 'Lesson 9',
        cards: [
          { type: CardType.VERB, value: 'glauben' },
          { type: CardType.VERB, value: 'halten' },
          { type: CardType.VERB, value: 'nennen' },
          { type: CardType.NOUN, value: 'Ende' },
          { type: CardType.NOUN, value: 'Million' },
          { type: CardType.NOUN, value: 'Schule' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'verschieden' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'bestimmt' },
        ],
      },
      {
        id: 10,
        title: 'Lesson 10',
        cards: [
          { type: CardType.VERB, value: 'mögen' },
          { type: CardType.VERB, value: 'zeigen' },
          { type: CardType.VERB, value: 'führen' },
          { type: CardType.NOUN, value: 'Woche' },
          { type: CardType.NOUN, value: 'Vater' },
          { type: CardType.NOUN, value: 'Seite' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'schnell' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'sicher' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'nächste' },
        ],
      },
      {
        id: 11,
        title: 'Lesson 11',
        cards: [
          { type: CardType.VERB, value: 'sprechen' },
          { type: CardType.VERB, value: 'bringen' },
          { type: CardType.VERB, value: 'leben' },
          { type: CardType.NOUN, value: 'Leben' },
          { type: CardType.NOUN, value: 'Mutter' },
          { type: CardType.NOUN, value: 'Grund' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'politisch' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'klar' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'schwer' },
        ],
      },
      {
        id: 12,
        title: 'Lesson 12',
        cards: [
          { type: CardType.VERB, value: 'fahren' },
          { type: CardType.VERB, value: 'meinen' },
          { type: CardType.VERB, value: 'fragen' },
          { type: CardType.NOUN, value: 'Auge' },
          { type: CardType.NOUN, value: 'Wort' },
          { type: CardType.NOUN, value: 'Geld' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'einzeln' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'bekannt' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'leicht' },
        ],
      },
      {
        id: 13,
        title: 'Lesson 13',
        cards: [
          { type: CardType.VERB, value: 'kennen' },
          { type: CardType.VERB, value: 'gelten' },
          { type: CardType.VERB, value: 'stellen' },
          { type: CardType.NOUN, value: 'Art' },
          { type: CardType.NOUN, value: 'Bereich' },
          { type: CardType.NOUN, value: 'Weg' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'rund' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'frei' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'früh' },
        ],
      },
      {
        id: 14,
        title: 'Lesson 14',
        cards: [
          { type: CardType.VERB, value: 'spielen' },
          { type: CardType.VERB, value: 'arbeiten' },
          { type: CardType.VERB, value: 'brauchen' },
          { type: CardType.NOUN, value: 'Stunde' },
          { type: CardType.NOUN, value: 'Name' },
          { type: CardType.NOUN, value: 'Geschichte' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'unterschiedlich' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'schlecht' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'deutlich' },
        ],
      },
      {
        id: 15,
        title: 'Lesson 15',
        cards: [
          { type: CardType.VERB, value: 'folgen' },
          { type: CardType.VERB, value: 'lernen' },
          { type: CardType.VERB, value: 'bestehen' },
          { type: CardType.NOUN, value: 'Gesellschaft' },
          { type: CardType.NOUN, value: 'Kopf' },
          { type: CardType.NOUN, value: 'Paar' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'allgemein' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'einzig' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'gemeinsam' },
        ],
      },
      {
        id: 16,
        title: 'Lesson 16',
        cards: [
          { type: CardType.VERB, value: 'verstehen' },
          { type: CardType.VERB, value: 'setzen' },
          { type: CardType.VERB, value: 'bekommen' },
          { type: CardType.NOUN, value: 'Möglichkeit' },
          { type: CardType.NOUN, value: 'Unternehmen' },
          { type: CardType.NOUN, value: 'Bild' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'nah' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'voll' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'direkt' },
        ],
      },
      {
        id: 17,
        title: 'Lesson 17',
        cards: [
          { type: CardType.VERB, value: 'beginnen' },
          { type: CardType.VERB, value: 'erzählen' },
          { type: CardType.VERB, value: 'versuchen' },
          { type: CardType.NOUN, value: 'Buch' },
          { type: CardType.NOUN, value: 'Wasser' },
          { type: CardType.NOUN, value: 'Stelle' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'international' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'sozial' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'beste' },
        ],
      },
      {
        id: 18,
        title: 'Lesson 18',
        cards: [
          { type: CardType.VERB, value: 'schreiben' },
          { type: CardType.VERB, value: 'laufen' },
          { type: CardType.VERB, value: 'erklären' },
          { type: CardType.NOUN, value: 'Form' },
          { type: CardType.NOUN, value: 'Entwicklung' },
          { type: CardType.NOUN, value: 'Monat' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'rot' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'offen' },
        ],
      },
      {
        id: 19,
        title: 'Lesson 19',
        cards: [
          { type: CardType.VERB, value: 'entsprechen' },
          { type: CardType.VERB, value: 'sitzen' },
          { type: CardType.VERB, value: 'ziehen' },
          { type: CardType.NOUN, value: 'Familie' },
          { type: CardType.NOUN, value: 'Morgen' },
          { type: CardType.NOUN, value: 'Abend' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'besondere' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'gewiss' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'öffentlich' },
        ],
      },
      {
        id: 20,
        title: 'Lesson 20',
        cards: [
          { type: CardType.VERB, value: 'scheinen' },
          { type: CardType.VERB, value: 'fallen' },
          { type: CardType.VERB, value: 'gehören' },
          { type: CardType.NOUN, value: 'Aufgabe' },
          { type: CardType.NOUN, value: 'Universität' },
          { type: CardType.NOUN, value: 'Sinn' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'halb' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'wahrscheinlich' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'europäisch' },
        ],
      },
      {
        id: 21,
        title: 'Lesson 21',
        cards: [
          { type: CardType.VERB, value: 'entstehen' },
          { type: CardType.VERB, value: 'erhalten' },
          { type: CardType.VERB, value: 'treffen' },
          { type: CardType.NOUN, value: 'Staat' },
          { type: CardType.NOUN, value: 'Ziel' },
          { type: CardType.NOUN, value: 'Freund' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'wesentlich' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'ähnlich' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'häufig' },
        ],
      },
      {
        id: 22,
        title: 'Lesson 22',
        cards: [
          { type: CardType.VERB, value: 'suchen' },
          { type: CardType.VERB, value: 'legen' },
          { type: CardType.VERB, value: 'vorstellen' },
          { type: CardType.NOUN, value: 'Thema' },
          { type: CardType.NOUN, value: 'Person' },
          { type: CardType.NOUN, value: 'Euro' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'schwarz' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'völlig' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'gering' },
        ],
      },
      {
        id: 23,
        title: 'Lesson 23',
        cards: [
          { type: CardType.VERB, value: 'handeln' },
          { type: CardType.VERB, value: 'erreichen' },
          { type: CardType.VERB, value: 'tragen' },
          { type: CardType.NOUN, value: 'Nacht' },
          { type: CardType.NOUN, value: 'Ding' },
          { type: CardType.NOUN, value: 'Raum' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'schwierig' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'praktisch' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'persönlich' },
        ],
      },
      {
        id: 24,
        title: 'Lesson 24',
        cards: [
          { type: CardType.VERB, value: 'schaffen' },
          { type: CardType.VERB, value: 'lesen' },
          { type: CardType.VERB, value: 'verlieren' },
          { type: CardType.NOUN, value: 'Blick' },
          { type: CardType.NOUN, value: 'Platz' },
          { type: CardType.NOUN, value: 'Zahl' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'modern' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'tief' },
        ],
      },
      {
        id: 25,
        title: 'Lesson 25',
        cards: [
          { type: CardType.VERB, value: 'darstellen' },
          { type: CardType.VERB, value: 'erkennen' },
          { type: CardType.VERB, value: 'entwickeln' },
          { type: CardType.NOUN, value: 'System' },
          { type: CardType.NOUN, value: 'Uhr' },
          { type: CardType.NOUN, value: 'Elter' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'tatsächlich' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'zusätzlich' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'wirtschaftlich' },
        ],
      },
      {
        id: 26,
        title: 'Lesson 26',
        cards: [
          { type: CardType.VERB, value: 'reden' },
          { type: CardType.VERB, value: 'aussehen' },
          { type: CardType.VERB, value: 'erscheinen' },
          { type: CardType.NOUN, value: 'Straße' },
          { type: CardType.NOUN, value: 'Minute' },
          { type: CardType.NOUN, value: 'Gruppe' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'interessant' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'relativ' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'gleichzeitig' },
        ],
      },
      {
        id: 27,
        title: 'Lesson 27',
        cards: [
          { type: CardType.VERB, value: 'bilden' },
          { type: CardType.VERB, value: 'anfangen' },
          { type: CardType.VERB, value: 'erwarten' },
          { type: CardType.NOUN, value: 'Wert' },
          { type: CardType.NOUN, value: 'Gesicht' },
          { type: CardType.NOUN, value: 'Sprache' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'grün' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'weiß' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'gesamt' },
        ],
      },
      {
        id: 28,
        title: 'Lesson 28',
        cards: [
          { type: CardType.VERB, value: 'wohnen' },
          { type: CardType.VERB, value: 'betreffen' },
          { type: CardType.VERB, value: 'warten' },
          { type: CardType.NOUN, value: 'Anfang' },
          { type: CardType.NOUN, value: 'Ort' },
          { type: CardType.NOUN, value: 'Moment' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'speziell' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'entscheidend' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'eng' },
        ],
      },
      {
        id: 29,
        title: 'Lesson 29',
        cards: [
          { type: CardType.VERB, value: 'vergehen' },
          { type: CardType.VERB, value: 'helfen' },
          { type: CardType.VERB, value: 'gewinnen' },
          { type: CardType.NOUN, value: 'Folge' },
          { type: CardType.NOUN, value: 'Interesse' },
          { type: CardType.NOUN, value: 'Milliarde' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'technisch' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'langsam' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'ständig' },
        ],
      },
      {
        id: 30,
        title: 'Lesson 30',
        cards: [
          { type: CardType.VERB, value: 'schließen' },
          { type: CardType.VERB, value: 'fühlen' },
          { type: CardType.VERB, value: 'bieten' },
          { type: CardType.NOUN, value: 'Rolle' },
          { type: CardType.NOUN, value: 'Tür' },
          { type: CardType.NOUN, value: 'Schüler' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'notwendig' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'rein' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'englisch' },
        ],
      },
      {
        id: 31,
        title: 'Lesson 31',
        cards: [
          { type: CardType.VERB, value: 'interessieren' },
          { type: CardType.VERB, value: 'erinnern' },
          { type: CardType.VERB, value: 'ergeben' },
          { type: CardType.NOUN, value: 'Bedeutung' },
          { type: CardType.NOUN, value: 'Text' },
          { type: CardType.NOUN, value: 'Ergebnis' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'wissenschaftlich' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'falsch' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'fremd' },
        ],
      },
      {
        id: 32,
        title: 'Lesson 32',
        cards: [
          { type: CardType.VERB, value: 'anbieten' },
          { type: CardType.VERB, value: 'studieren' },
          { type: CardType.VERB, value: 'verbinden' },
          { type: CardType.NOUN, value: 'Krieg' },
          { type: CardType.NOUN, value: 'Weise' },
          { type: CardType.NOUN, value: 'Regierung' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'selten' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'normal' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'wahr' },
        ],
      },
      {
        id: 33,
        title: 'Lesson 33',
        cards: [
          { type: CardType.VERB, value: 'ansehen' },
          { type: CardType.VERB, value: 'fehlen' },
          { type: CardType.VERB, value: 'bedeuten' },
          { type: CardType.NOUN, value: 'Stück' },
          { type: CardType.NOUN, value: 'Wohnung' },
          { type: CardType.NOUN, value: 'Gespräch' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'privat' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'tot' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'fest' },
        ],
      },
      {
        id: 34,
        title: 'Lesson 34',
        cards: [
          { type: CardType.VERB, value: 'vergleichen' },
          { type: CardType.VERB, value: 'steigen' },
          { type: CardType.VERB, value: 'nutzen' },
          { type: CardType.NOUN, value: 'Meter' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'positiv' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'zentral' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'fertig' },
        ],
      },
    ],
  },
  {
    id: 1,
    title: 'My German',
    lessons: [
      {
        id: 1,
        title: 'Articles',
        cards: [
          {
            type: CardType.ARTICLE,
            value: 'der',
          },
          {
            type: CardType.ARTICLE,
            value: 'dieF',
          },
          {
            type: CardType.ARTICLE,
            value: 'das',
          },
          {
            type: CardType.ARTICLE,
            value: 'dieP',
          },
          {
            type: CardType.ARTICLE,
            value: 'einM',
          },
          {
            type: CardType.ARTICLE,
            value: 'eine',
          },
          {
            type: CardType.ARTICLE,
            value: 'einN',
          },
        ],
      },
      {
        id: 2,
        title: 'Phrases',
        cards: [
          { type: CardType.PHRASE, value: 'Prost' },
          { type: CardType.PHRASE, value: 'ph-Bitte' },
          { type: CardType.PHRASE, value: 'Tschüss' },
        ],
      },
      {
        id: 3,
        title: 'Prepositions',
        cards: [
          { type: CardType.PREPOSITION, value: 'auf' },
          { type: CardType.PREPOSITION, value: 'in' },
          { type: CardType.PREPOSITION, value: 'um' },
          { type: CardType.PREPOSITION, value: 'für' },
        ],
      },
      {
        id: 4,
        title: 'Pronouns 1',
        cards: [
          { type: CardType.PRONOUN, value: 'ich' },
          { type: CardType.PRONOUN, value: 'du' },
          { type: CardType.PRONOUN, value: 'er' },
          { type: CardType.PRONOUN, value: 'mein' },
        ],
      },
      {
        id: 5,
        title: 'Possessive pronouns',
        cards: [
          { type: CardType.PRONOUN, value: 'mein' },
          { type: CardType.PRONOUN, value: 'dein' },
          { type: CardType.PRONOUN, value: 'pr-sein' },
          { type: CardType.PRONOUN, value: 'ihrer' },
          { type: CardType.PRONOUN, value: 'unser' },
          { type: CardType.PRONOUN, value: 'euer' },
        ],
      },
      {
        id: 6,
        title: 'Custom verbs',
        cards: [
          // { type: CardType.VERB, value: 'zurücksetzen' },
          // { type: CardType.VERB, value: 'freuen' },
          // { type: CardType.VERB, value: 'wohnen' },
          // { type: CardType.VERB, value: 'bewundern' },
          // { type: CardType.VERB, value: 'tun' },
          // { type: CardType.VERB, value: 'dastehen' },
          // { type: CardType.VERB, value: 'können' },
          { type: CardType.VERB, value: 'machen' },
          // { type: CardType.VERB, value: 'sein' },
          // { type: CardType.VERB, value: 'freuen' },
        ],
      },
      {
        id: 7,
        title: 'test',
        cards: [
          // { type: CardType.VERB, value: 'beginnen' },
          { type: CardType.VERB, value: 'sein' },
          // { type: CardType.VERB, value: 'regnen' },
          // { type: CardType.NOUN, value: 'Kopf' },
          // { type: CardType.ADJECTIVE, value: 'spät' },
          // { type: CardType.NOUN, value: 'Leute' },
          // { type: CardType.ADJECTIVE, value: 'ganz' },
          // { type: CardType.ADJECTIVE, value: 'hoch' },
          // { type: CardType.ADJECTIVE, value: 'neu' },
          // { type: CardType.PRONOUN, value: 'alle' },
        ],
      },
      {
        id: 8,
        title: 'Times',
        cards: [
          { type: CardType.NOUN, value: 'Montag' },
          { type: CardType.NOUN, value: 'Dienstag' },
          { type: CardType.NOUN, value: 'Mittwoch' },
          { type: CardType.NOUN, value: 'Donnerstag' },
          { type: CardType.NOUN, value: 'Freitag' },
          { type: CardType.NOUN, value: 'Samstag' },
          { type: CardType.NOUN, value: 'Sonntag' },
          { type: CardType.NOUN, value: 'Januar' },
          { type: CardType.NOUN, value: 'Februar' },
          { type: CardType.NOUN, value: 'März' },
          { type: CardType.NOUN, value: 'April' },
          { type: CardType.NOUN, value: 'Mai' },
          { type: CardType.NOUN, value: 'Juni' },
          { type: CardType.NOUN, value: 'Juli' },
          { type: CardType.NOUN, value: 'August' },
          { type: CardType.NOUN, value: 'September' },
          { type: CardType.NOUN, value: 'Oktober' },
          { type: CardType.NOUN, value: 'November' },
          { type: CardType.NOUN, value: 'Dezember' },
          { type: CardType.NOUN, value: 'Frühling' },
          { type: CardType.NOUN, value: 'Winter' },
          { type: CardType.NOUN, value: 'Sommer' },
          { type: CardType.NOUN, value: 'Herbst' },
          { type: CardType.NOUN, value: 'Sekunde' },
          { type: CardType.NOUN, value: 'Millisekunde' },
          { type: CardType.NOUN, value: 'Minute' },
          { type: CardType.NOUN, value: 'Stunde' },
          { type: CardType.NOUN, value: 'Woche' },
          { type: CardType.NOUN, value: 'Tag' },
          { type: CardType.NOUN, value: 'Monat' },
          { type: CardType.NOUN, value: 'Jahr' },
          { type: CardType.NOUN, value: 'Jahrzehnt' },
          { type: CardType.NOUN, value: 'Jahrhundert' },
          { type: CardType.NOUN, value: 'Jahrtausend' },
        ],
      },
      {
        id: 9,
        title: 'Colors',
        cards: [
          { type: CardType.NOUN, value: 'Farbe' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'schwarz' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'weiß' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'rot' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'grün' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'blau' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'gelb' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'grau' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'orange' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'rosa' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'violett' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'lila' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'braun' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'beige' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'türkis' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'magenta' },
        ],
      },
      {
        id: 10,
        title: 'Body parts',
        cards: [
          { type: CardType.NOUN, value: 'Kopf' },
          { type: CardType.NOUN, value: 'Auge' },
          { type: CardType.NOUN, value: 'Mund' },
          { type: CardType.NOUN, value: 'Nase' },
          { type: CardType.NOUN, value: 'Ohr' },
          { type: CardType.NOUN, value: 'Hals' },
          { type: CardType.NOUN, value: 'Arm' },
          { type: CardType.NOUN, value: 'Hand' },
          { type: CardType.NOUN, value: 'Finger' },
          { type: CardType.NOUN, value: 'Bein' },
          { type: CardType.NOUN, value: 'Fuß' },
          { type: CardType.NOUN, value: 'Herz' },
          { type: CardType.NOUN, value: 'Lunge' },
          { type: CardType.NOUN, value: 'Magen' },
          { type: CardType.NOUN, value: 'Leber' },
          { type: CardType.NOUN, value: 'Gehirn' },
          { type: CardType.NOUN, value: 'Niere' },
          { type: CardType.NOUN, value: 'Rücken' },
          { type: CardType.NOUN, value: 'Haut' },
          { type: CardType.NOUN, value: 'Bauch' },
        ],
      },
      {
        id: 11,
        title: 'Family',
        cards: [
          { type: CardType.NOUN, value: 'Mutter' },
          { type: CardType.NOUN, value: 'Vater' },
          { type: CardType.NOUN, value: 'Sohn' },
          { type: CardType.NOUN, value: 'Tochter' },
          { type: CardType.NOUN, value: 'Kind' },
          { type: CardType.NOUN, value: 'Elter' },
          { type: CardType.NOUN, value: 'Bruder' },
          { type: CardType.NOUN, value: 'Schwester' },
          { type: CardType.NOUN, value: 'Großmutter' },
          { type: CardType.NOUN, value: 'Großvater' },
          { type: CardType.NOUN, value: 'Onkel' },
          { type: CardType.NOUN, value: 'Tante' },
          { type: CardType.NOUN, value: 'Neffe' },
          { type: CardType.NOUN, value: 'Nichte' },
          { type: CardType.NOUN, value: 'Cousin' },
          { type: CardType.NOUN, value: 'Schwiegervater' },
          { type: CardType.NOUN, value: 'Schwiegermutter' },
          { type: CardType.NOUN, value: 'Schwager' },
          { type: CardType.NOUN, value: 'Schwägerin' },
        ],
      },
      {
        id: 12,
        title: 'Professions',
        cards: [
          { type: CardType.NOUN, value: 'Arzt' },
          { type: CardType.NOUN, value: 'Ingenieur' },
          { type: CardType.NOUN, value: 'Lehrer' },
          { type: CardType.NOUN, value: 'Koch' },
          { type: CardType.NOUN, value: 'Polizist' },
          { type: CardType.NOUN, value: 'Mechaniker' },
          { type: CardType.NOUN, value: 'Anwalt' },
          { type: CardType.NOUN, value: 'Verkäufer' },
          { type: CardType.NOUN, value: 'Manager' },
          { type: CardType.NOUN, value: 'Elektriker' },
          { type: CardType.NOUN, value: 'Bauarbeiter' },
          { type: CardType.NOUN, value: 'Fahrer' },
          { type: CardType.NOUN, value: 'Gärtner' },
          { type: CardType.NOUN, value: 'Journalist' },
          { type: CardType.NOUN, value: 'Fotograf' },
          { type: CardType.NOUN, value: 'Programmierer' },
          { type: CardType.NOUN, value: 'Schriftsteller' },
          { type: CardType.NOUN, value: 'Direktor' },
          { type: CardType.NOUN, value: 'Banker' },
          { type: CardType.NOUN, value: 'Pilot' },
        ],
      },
      {
        id: 13,
        title: 'Home',
        cards: [
          { type: CardType.NOUN, value: 'Stuhl' },
          { type: CardType.NOUN, value: 'Tisch' },
          { type: CardType.NOUN, value: 'Sofa' },
          { type: CardType.NOUN, value: 'Bett' },
          { type: CardType.NOUN, value: 'Schrank' },
          { type: CardType.NOUN, value: 'Lampe' },
          { type: CardType.NOUN, value: 'Teppich' },
          { type: CardType.NOUN, value: 'Spiegel' },
          { type: CardType.NOUN, value: 'Kommode' },
          { type: CardType.NOUN, value: 'Sessel' },
          { type: CardType.NOUN, value: 'Couch' },
          { type: CardType.NOUN, value: 'Hocker' },
          { type: CardType.NOUN, value: 'Schreibtisch' },
          { type: CardType.NOUN, value: 'Vase' },
          { type: CardType.NOUN, value: 'Regal' },
          { type: CardType.NOUN, value: 'Gardine' },
          { type: CardType.NOUN, value: 'Matratze' },
          { type: CardType.NOUN, value: 'Kissen' },
          { type: CardType.NOUN, value: 'Uhr' },
          { type: CardType.NOUN, value: 'Löffel' },
          { type: CardType.NOUN, value: 'Gabel' },
          { type: CardType.NOUN, value: 'Messer' },
          { type: CardType.NOUN, value: 'Teller' },
          { type: CardType.NOUN, value: 'Schüssel' },
          { type: CardType.NOUN, value: 'Becher' },
          { type: CardType.NOUN, value: 'Glas' },
          { type: CardType.NOUN, value: 'Besteck' },
          { type: CardType.NOUN, value: 'Vorhang' },
          { type: CardType.NOUN, value: 'Kühlschrank' },
          { type: CardType.NOUN, value: 'Mikrowelle' },
          { type: CardType.NOUN, value: 'Tür' },
          { type: CardType.NOUN, value: 'Fenster' },
          { type: CardType.NOUN, value: 'Drucker' },
          { type: CardType.NOUN, value: 'Brettspiel' },
          { type: CardType.NOUN, value: 'Kleiderschrank' },
          { type: CardType.NOUN, value: 'Flasche' },
          { type: CardType.NOUN, value: 'Gasherd' },
          { type: CardType.NOUN, value: 'Geschirrspülmaschine' },
          { type: CardType.NOUN, value: 'Waschmaschine' },
          { type: CardType.NOUN, value: 'Dusche' },
          { type: CardType.NOUN, value: 'Waschbecken' },
          { type: CardType.NOUN, value: 'Zahnbürste' },
          { type: CardType.NOUN, value: 'Alkohol' },
          { type: CardType.NOUN, value: 'Blume' },
          { type: CardType.NOUN, value: 'Kleidung' },
          { type: CardType.NOUN, value: 'Heizkörper' },
          { type: CardType.NOUN, value: 'Serviette' },
          { type: CardType.NOUN, value: 'Bügeleisen' },
          { type: CardType.NOUN, value: 'Yogamatte' },
          { type: CardType.NOUN, value: 'Handy' },
          { type: CardType.NOUN, value: 'Fernbedienung' },
          { type: CardType.NOUN, value: 'Kabel' },
          { type: CardType.NOUN, value: 'Schlafzimmer' },
          { type: CardType.NOUN, value: 'Wohnzimmer' },
          { type: CardType.NOUN, value: 'Küche' },
          { type: CardType.NOUN, value: 'Staubsauger' },
          { type: CardType.NOUN, value: 'Boden' },
          { type: CardType.NOUN, value: 'Decke' },
          { type: CardType.NOUN, value: 'Mauer' },
          { type: CardType.NOUN, value: 'Guckloch' },
          { type: CardType.NOUN, value: 'Toilette' },
          { type: CardType.NOUN, value: 'Urinal' },
          { type: CardType.NOUN, value: 'Tastatur' },
          { type: CardType.NOUN, value: 'Maus' },
          { type: CardType.NOUN, value: 'Computer' },
        ],
      },
      {
        id: 14,
        title: 'WH questions',
        cards: [
          { type: CardType.PRONOUN, value: 'wer' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'was' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'wann' },
          { type: CardType.CONJUNCTION, value: 'wo' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'warum' },
          { type: CardType.CONJUNCTION, value: 'wie' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'wozu' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'woher' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'wohin' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'wofür' },
          { type: CardType.PRONOUN, value: 'welcher' },
        ],
      },
    ],
  },
  {
    id: 4,
    title: 'LingQ lessons',
    lessons: [
      {
        id: 1,
        title: '1',
        cards: [
          { type: CardType.PHRASE, value: 'Hallo' },
          { type: CardType.CONJUNCTION, value: 'wie' },
          { type: CardType.NOUN, value: 'Gut' },
          { type: CardType.CONJUNCTION, value: 'und' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'super' },
          { type: CardType.PHRASE, value: 'Prost' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'was' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'neu' },
          { type: CardType.NOUN, value: 'Passwort' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'echt' },
          { type: CardType.CONJUNCTION, value: 'wo' },
          { type: CardType.CONJUNCTION, value: 'denn' },
          { type: CardType.NOUN, value: 'Ahnung' },
          { type: CardType.VERB, value: 'haben' },
          { type: CardType.VERB, value: 'vergessen' },
          { type: CardType.VERB, value: 'scheißen' },
          { type: CardType.VERB, value: 'tun' },
          { type: CardType.NOUN, value: 'Problem' },
          { type: CardType.NOUN, value: 'Entschuldigung' },
          { type: CardType.NOUN, value: 'Toilette' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'hier' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'auch' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'fremd' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'so' },
          { type: CardType.CONJUNCTION, value: 'aber' },
          { type: CardType.VERB, value: 'glauben' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'vorhin' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'da' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'hinten' },
          { type: CardType.NOUN, value: 'Ende' },
          { type: CardType.PHRASE, value: 'Danke' },
          { type: CardType.NOUN, value: 'Bitte' },
          { type: CardType.VERB, value: 'müssen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'jetzt' },
          { type: CardType.VERB, value: 'gehen' },
          { type: CardType.PHRASE, value: 'Tschüss' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'viel' },
          { type: CardType.NOUN, value: 'Glück' },
          { type: CardType.VERB, value: 'lieben' },
          { type: CardType.PHRASE, value: 'Los' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'wohin' },
          { type: CardType.PREPOSITION, value: 'in' },
          { type: CardType.NOUN, value: 'Zukunft' },
          { type: CardType.VERB, value: 'klingen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'gut' },
          { type: CardType.VERB, value: 'freuen' },
          { type: CardType.VERB, value: 'leiden' },
          { type: CardType.PHRASE, value: 'Ach' },
          { type: CardType.VERB, value: 'sehen' },
          { type: CardType.NOUN, value: 'Gang' },
          { type: CardType.VERB, value: 'danken' },
        ],
      },

      {
        id: 2,
        title: '2',
        cards: [
          { type: CardType.ADJECTIVE_ADVERB, value: 'ja' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'heute' },
          { type: CardType.NOUN, value: 'Tag' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'nein' },
          { type: CardType.CONJUNCTION, value: 'dass' },
          { type: CardType.VERB, value: 'fragen' },
          { type: CardType.VERB, value: 'funktionieren' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'nicht' },
          { type: CardType.VERB, value: 'versuchen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'nochmal' },
          { type: CardType.VERB, value: 'heißen' },
          { type: CardType.VERB, value: 'können' },
          { type: CardType.VERB, value: 'helfen' },
          { type: CardType.VERB, value: 'bitten' },
          { type: CardType.VERB, value: 'wiederholen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'interessant' },
          { type: CardType.VERB, value: 'zurücksetzen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'genau' },
          { type: CardType.NOUN, value: 'Büro' },
          { type: CardType.VERB, value: 'lassen' },
          { type: CardType.VERB, value: 'suchen' },
          { type: CardType.PREPOSITION, value: 'bis' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'spät' },
        ],
      },
      {
        id: 3,
        title: '3',
        cards: [
          { type: CardType.NOUN, value: 'Morgen' },
          { type: CardType.NOUN, value: 'Jahr' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'alt' },
          { type: CardType.VERB, value: 'wohnen' },
          { type: CardType.NOUN, value: 'Lehrer' },
          { type: CardType.NOUN, value: 'Deutsch' },
          { type: CardType.VERB, value: 'sprechen' },
          { type: CardType.NOUN, value: 'Name' },
          { type: CardType.VERB, value: 'kommen' },
          { type: CardType.PREPOSITION, value: 'aus' },
          { type: CardType.VERB, value: 'lernen' },
          { type: CardType.VERB, value: 'studieren' },
          { type: CardType.NOUN, value: 'Medizin' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'sehr' },
        ],
      },
      {
        id: 4,
        title: 'In einer Bar',
        cards: [
          { type: CardType.NOUN, value: 'Bar' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'gerade' },
          { type: CardType.NOUN, value: 'Projekt' },
          { type: CardType.PREPOSITION, value: 'bei' },
          { type: CardType.NOUN, value: 'Arbeit' },
          { type: CardType.VERB, value: 'beginnen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'geheim' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'also' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'darüber' },
          { type: CardType.VERB, value: 'erzählen' },
          { type: CardType.PHRASE, value: 'Schade' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'wirklich' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'spannend' },
          { type: CardType.PREPOSITION, value: 'für' },
        ],
      },
      {
        id: 5,
        title: 'Auf der Straße',
        cards: [
          { type: CardType.PREPOSITION, value: 'auf' },
          { type: CardType.NOUN, value: 'Straße' },
          { type: CardType.PREPOSITION, value: 'von' },
          { type: CardType.PHRASE, value: 'Na' },
          { type: CardType.VERB, value: 'machen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'natürlich' },
          { type: CardType.VERB, value: 'kosten' },
          { type: CardType.NOUN, value: 'Euro' },
          { type: CardType.VERB, value: 'geben' },
          { type: CardType.NOUN, value: 'Kaffee' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'ad-schon' },
          { type: CardType.VERB, value: 'warten' },
          { type: CardType.NOUN, value: 'Handy' },
          { type: CardType.VERB, value: 'leihen' },
        ],
      },
      {
        id: 6,
        title: 'In einem Restaurant',
        cards: [
          { type: CardType.NOUN, value: 'Restaurant' },
          { type: CardType.NOUN, value: 'Hunger' },
          { type: CardType.VERB, value: 'nehmen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'geil' },
          { type: CardType.NOUN, value: 'Essen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'lecker' },
          { type: CardType.VERB, value: 'stimmen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'satt' },
        ],
      },
      {
        id: 7,
        title: 'In einem Park',
        cards: [
          { type: CardType.NOUN, value: 'Park' },
          { type: CardType.NOUN, value: 'Hilfe' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'ein bisschen' },
          { type: CardType.VERB, value: 'verlaufen' },
          { type: CardType.NOUN, value: 'Angst' },
          { type: CardType.NOUN, value: 'Hotel' },
          { type: CardType.VERB, value: 'wissen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'nur' },
          { type: CardType.VERB, value: 'rufen' },
          { type: CardType.NOUN, value: 'Taxi' },
          { type: CardType.PREPOSITION, value: 'an' },
          { type: CardType.NOUN, value: 'Taxifahrer' },
          { type: CardType.VERB, value: 'brauchen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'viele' },
          { type: CardType.NOUN, value: 'Dank' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'gern' },
          { type: CardType.VERB, value: 'geschehen' },
          { type: CardType.VERB, value: 'hoffen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'bald' },
          { type: CardType.VERB, value: 'wiedersehen' },
        ],
      },
      {
        id: 9,
        title: 'An einem Bahnhof + Verben 1',
        cards: [
          { type: CardType.NOUN, value: 'Bahnhof' },
          { type: CardType.NOUN, value: 'Wiedersehen' },
          { type: CardType.NOUN, value: 'Verb' },
          { type: CardType.VERB, value: 'leben' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'klein' },
          { type: CardType.NOUN, value: 'Stadt' },
          { type: CardType.VERB, value: 'antworten' },
          { type: CardType.VERB, value: 'sagen' },
          { type: CardType.NOUN, value: 'Frühstück' },
          { type: CardType.NOUN, value: 'Durst' },
          { type: CardType.VERB, value: 'holen' },
          { type: CardType.NOUN, value: 'Wasser' },
          { type: CardType.PREPOSITION, value: 'nach' },
          { type: CardType.VERB, value: 'sollen' },
          { type: CardType.VERB, value: 'einkaufen' },
          { type: CardType.VERB, value: 'schlagen' },
          { type: CardType.PREPOSITION, value: 'vor' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'unterwegs' },
          { type: CardType.VERB, value: 'halten' },
          { type: CardType.PREPOSITION, value: 'um' },
          { type: CardType.NOUN, value: 'Blume' },
          { type: CardType.PREPOSITION, value: 'pre-zu' },
          { type: CardType.VERB, value: 'bewundern' },
          { type: CardType.VERB, value: 'schauen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'schön' },
          { type: CardType.VERB, value: 'zeigen' },
          { type: CardType.NOUN, value: 'Supermarkt' },
          { type: CardType.NOUN, value: 'Kundenkarte' },
          { type: CardType.NOUN, value: 'Heimweg' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'geradeaus' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'dann' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'links' },
          { type: CardType.VERB, value: 'erklären' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'müde' },
          { type: CardType.VERB, value: 'ruhen' },
          { type: CardType.VERB, value: 'einräumen' },
          { type: CardType.NOUN, value: 'Abend' },
          { type: CardType.PREPOSITION, value: 'mit' },
          { type: CardType.NOUN, value: 'Film' },
          { type: CardType.CONJUNCTION, value: 'bevor' },
          { type: CardType.VERB, value: 'schlafen' },
          { type: CardType.VERB, value: 'schalten' },
          { type: CardType.NOUN, value: 'Licht' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'bereit' },
        ],
      },

      {
        id: 10,
        title: 'V2',
        cards: [
          { type: CardType.ADJECTIVE_ADVERB, value: 'gestern' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'sofort' },
          { type: CardType.NOUN, value: 'Weg' },
          { type: CardType.VERB, value: 'werden' },
          { type: CardType.NOUN, value: 'Person' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'übermorgen' },
          { type: CardType.VERB, value: 'wollen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'letzte' },
          { type: CardType.NOUN, value: 'Woche' },
          { type: CardType.VERB, value: 'ausmachen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'nah' },
          { type: CardType.PREPOSITION, value: 'durch' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'immer' },
          { type: CardType.VERB, value: 'lächeln' },
          { type: CardType.NOUN, value: 'Plan' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'einfach' },
          { type: CardType.VERB, value: 'lachen' },
        ],
      },
      {
        id: 11,
        title: 'V3',
        cards: [
          { type: CardType.VERB, value: 'sichern' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'vielleicht' },
          { type: CardType.VERB, value: 'spazieren' },
          { type: CardType.VERB, value: 'regnen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'draußen' },
          { type: CardType.VERB, value: 'aufstehen' },
          { type: CardType.NOUN, value: 'Brot' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'traurig' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'warum' },
          { type: CardType.VERB, value: 'überraschen' },
          { type: CardType.VERB, value: 'erinnern' },
          { type: CardType.VERB, value: 'erwidern' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'morgen' },
          { type: CardType.NOUN, value: 'Kino' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'unsicher' },
          { type: CardType.CONJUNCTION, value: 'ob' },
          { type: CardType.NOUN, value: 'Zeit' },
          { type: CardType.VERB, value: 'kaufen' },
          { type: CardType.VERB, value: 'versprechen' },
          { type: CardType.PREPOSITION, value: 'ohne' },
          { type: CardType.VERB, value: 'mögen' },
          { type: CardType.NOUN, value: 'Fenster' },
          { type: CardType.VERB, value: 'schließen' },
          { type: CardType.NOUN, value: 'Vergangenheit' },
          { type: CardType.VERB, value: 'kochen' },
          { type: CardType.VERB, value: 'essen' },
          { type: CardType.VERB, value: 'vorschlagen' },
        ],
      },
      {
        id: 12,
        title: 'Gedanken – eins',
        cards: [
          { type: CardType.NOUN, value: 'Gedanke' },
          { type: CardType.NOUN, value: 'Stunde' },
          { type: CardType.NOUN, value: 'Minute' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'kalt' },
          { type: CardType.NOUN, value: 'Sonne' },
          { type: CardType.VERB, value: 'scheinen' },
          { type: CardType.NOUN, value: 'Gesicht' },
          { type: CardType.NOUN, value: 'Verkehrsampel' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'hungrig' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'durstig' },
          { type: CardType.VERB, value: 'trinken' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'wann' },
          { type: CardType.VERB, value: 'fahren' },
          { type: CardType.NOUN, value: 'Arschloch' },
          { type: CardType.VERB, value: 'abschließen' },
          { type: CardType.NOUN, value: 'Unsinn' },
          { type: CardType.VERB, value: 'schreiben' },
          { type: CardType.VERB, value: 'wünschen' },
          { type: CardType.NOUN, value: 'Wohnung' },
          { type: CardType.VERB, value: 'überqueren' },
          { type: CardType.NOUN, value: 'Zebrastreifen' },
          { type: CardType.NOUN, value: 'Ranzen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'schwer' },
          { type: CardType.NOUN, value: 'Wasserflasche' },
          { type: CardType.VERB, value: 'bewahren' },
          { type: CardType.NOUN, value: 'Hund' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'solcher' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'erst' },
          { type: CardType.NOUN, value: 'Mal' },
          { type: CardType.VERB, value: 'verlangen' },
          { type: CardType.NOUN, value: 'Satz' },
          { type: CardType.VERB, value: 'übersetzen' },
          { type: CardType.NOUN, value: 'Gott' },
          { type: CardType.VERB, value: 'töten' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'hoffentlich' },
          { type: CardType.VERB, value: 'schmecken' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'fast' },
          { type: CardType.VERB, value: 'aufladen' },
          { type: CardType.VERB, value: 'einladen' },
          { type: CardType.CONJUNCTION, value: 'wenn' },
          { type: CardType.VERB, value: 'anfangen' },
          { type: CardType.NOUN, value: 'Nuss' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'deutsch' },
          { type: CardType.NOUN, value: 'Wort' },
          { type: CardType.VERB, value: 'ausdrucken' },
          { type: CardType.NOUN, value: 'Ding' },
          { type: CardType.VERB, value: 'hängen' },
          { type: CardType.NOUN, value: 'Lied' },
          { type: CardType.VERB, value: 'singen' },
          { type: CardType.VERB, value: 'gehören' },
          { type: CardType.NOUN, value: 'Recht' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'langsam' },
          { type: CardType.NOUN, value: 'Jugendlichkeit' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'schnell' },
          { type: CardType.NOUN, value: 'Stau' },
          { type: CardType.NOUN, value: 'Nähe' },
          { type: CardType.VERB, value: 'öffnen' },
          { type: CardType.CONJUNCTION, value: 'als' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'schläfrig' },
          { type: CardType.VERB, value: 'einschlafen' },
        ],
      },
      {
        id: 13,
        title: 'Fragen',
        cards: [
          { type: CardType.ADJECTIVE_ADVERB, value: 'leider' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'einig' },
          { type: CardType.VERB, value: 'besprechen' },
          { type: CardType.VERB, value: 'verraten' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'woher' },
          { type: CardType.NOUN, value: 'Familie' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'groß' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'insgesamt' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'beruflich' },
          { type: CardType.VERB, value: 'arbeiten' },
          { type: CardType.NOUN, value: 'Marketing' },
          { type: CardType.NOUN, value: 'Geschwister' },
          { type: CardType.NOUN, value: 'Bruder' },
          { type: CardType.NOUN, value: 'Schwester' },
          { type: CardType.NOUN, value: 'Hobby' },
          { type: CardType.VERB, value: 'lesen' },
          { type: CardType.VERB, value: 'wandern' },
          { type: CardType.VERB, value: 'spielen' },
          { type: CardType.NOUN, value: 'Fußball' },
          { type: CardType.NOUN, value: 'Job' },
          { type: CardType.NOUN, value: 'Kultur' },
          { type: CardType.NOUN, value: 'Sprache' },
          { type: CardType.NOUN, value: 'Urlaub' },
          { type: CardType.NOUN, value: 'Winter' },
          { type: CardType.NOUN, value: 'Frühling' },
          { type: CardType.NOUN, value: 'Sommer' },
          { type: CardType.NOUN, value: 'Herbst' },
          { type: CardType.VERB, value: 'bleiben' },
          { type: CardType.VERB, value: 'entspannen' },
          { type: CardType.NOUN, value: 'Liebling' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'lang' },
          { type: CardType.PREPOSITION, value: 'seit' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'kürzlich' },
          { type: CardType.NOUN, value: 'Monat' },
          { type: CardType.NOUN, value: 'Favorit' },
          { type: CardType.NOUN, value: 'Haustier' },
          { type: CardType.NOUN, value: 'Instrument' },
          { type: CardType.NOUN, value: 'Klavier' },
          { type: CardType.NOUN, value: 'Gitarre' },
          { type: CardType.NOUN, value: 'Musik' },
          { type: CardType.VERB, value: 'aufhören' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'lieb' },
          { type: CardType.NOUN, value: 'Mischung' },
        ],
      },
    ],
  },
  {
    id: 5,
    title: 'Nk',
    lessons: [
      {
        id: 1,
        title: '1',
        cards: [
          {
            type: CardType.NOUN,
            value: 'Eile',
          },
          {
            type: CardType.ADJECTIVE_ADVERB,
            value: 'reinlich',
          },
          {
            type: CardType.VERB,
            value: 'entzweien',
          },
          {
            type: CardType.NOUN,
            value: 'Dreck',
          },
          {
            type: CardType.ADJECTIVE_ADVERB,
            value: 'andauernd',
          },
          {
            type: CardType.ADJECTIVE_ADVERB,
            value: 'unlängst',
          },
          {
            type: CardType.NOUN,
            value: 'Tonfall',
          },
          {
            type: CardType.ADJECTIVE_ADVERB,
            value: 'fleißig',
          },
          {
            type: CardType.ADJECTIVE_ADVERB,
            value: 'hierdurch',
          },
          {
            type: CardType.NOUN,
            value: 'Beichte',
          },
          {
            type: CardType.NOUN,
            value: 'Pfütze',
          },
          {
            type: CardType.NOUN,
            value: 'Pfote',
          },
          {
            type: CardType.ADJECTIVE_ADVERB,
            value: 'trübe',
          },
          {
            type: CardType.NOUN,
            value: 'Unverschämtheit',
          },
          {
            type: CardType.NOUN,
            value: 'Lüsternheit',
          },
          {
            type: CardType.VERB,
            value: 'leimen',
          },
          {
            type: CardType.VERB,
            value: 'jauchzen',
          },
          {
            type: CardType.VERB,
            value: 'läuten',
          },
          {
            type: CardType.VERB,
            value: 'hinausfliegen',
          },
          {
            type: CardType.NOUN,
            value: 'Tropfen',
          },
          {
            type: CardType.NOUN,
            value: 'Regentropfen',
          },
          {
            type: CardType.ADJECTIVE_ADVERB,
            value: 'unverkennbar',
          },
          {
            type: CardType.VERB,
            value: 'ausstehen',
          },
          {
            type: CardType.NOUN,
            value: 'Abfluss',
          },
          {
            type: CardType.ADJECTIVE_ADVERB,
            value: 'überdies',
          },
          {
            type: CardType.NOUN,
            value: 'Kessel',
          },
          {
            type: CardType.VERB,
            value: 'verdauen',
          },
          {
            type: CardType.NOUN,
            value: 'Kleingeld',
          },
          {
            type: CardType.ADJECTIVE_ADVERB,
            value: 'anspruchsvoll',
          },
          {
            type: CardType.ADJECTIVE_ADVERB,
            value: 'keck',
          },
          {
            type: CardType.VERB,
            value: 'weiden',
          },
          {
            type: CardType.ADJECTIVE_ADVERB,
            value: 'aufregend',
          },
          {
            type: CardType.NOUN,
            value: 'Bammel',
          },
          {
            type: CardType.ADJECTIVE_ADVERB,
            value: 'fragwürdig',
          },
          {
            type: CardType.ADJECTIVE_ADVERB,
            value: 'unversehens',
          },
          {
            type: CardType.NOUN,
            value: 'Ankunft',
          },
          {
            type: CardType.VERB,
            value: 'verdrießen',
          },
          {
            type: CardType.VERB,
            value: 'begehren',
          },
          {
            type: CardType.ADJECTIVE_ADVERB,
            value: 'umgehend',
          },
          {
            type: CardType.ADJECTIVE_ADVERB,
            value: 'zielstrebig',
          },
          {
            type: CardType.ADJECTIVE_ADVERB,
            value: 'preiswert',
          },
          {
            type: CardType.ADJECTIVE_ADVERB,
            value: 'tapfer',
          },
          {
            type: CardType.NOUN,
            value: 'Verstand',
          },
          {
            type: CardType.VERB,
            value: 'abschwächen',
          },
          {
            type: CardType.NOUN,
            value: 'Entlassung',
          },
          {
            type: CardType.NOUN,
            value: 'Vorgehensweise',
          },
          {
            type: CardType.NOUN,
            value: 'Sünde',
          },
          {
            type: CardType.ADJECTIVE_ADVERB,
            value: 'unpassend',
          },
          {
            type: CardType.ADJECTIVE_ADVERB,
            value: 'fahrlässig',
          },
          {
            type: CardType.NOUN,
            value: 'Versteifung',
          },
        ],
      },
    ],
  },
  {
    id: 6,
    title: 'Die Biene Maja',
    lessons: [
      {
        id: 1,
        title: 'S01E01 p1',
        cards: [
          { type: CardType.PREPOSITION, value: 'in' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'unbekannt' },
          { type: CardType.NOUN, value: 'Land' },
          { type: CardType.PREPOSITION, value: 'vor' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'gar' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'nicht' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'allzu' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'lang' },
          { type: CardType.NOUN, value: 'Zeit' },
          { type: CardType.NOUN, value: 'Biene' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'sehr' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'bekannt' },
          { type: CardType.PREPOSITION, value: 'von' },
          { type: CardType.VERB, value: 'sprechen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'weit' },
          { type: CardType.CONJUNCTION, value: 'und' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'breit' },
          { type: CardType.VERB, value: 'nennen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'klein' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'frech' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'schlau' },
          { type: CardType.VERB, value: 'lieben' },
          { type: CardType.PRONOUN, value: 'alle' },
          { type: CardType.NOUN, value: 'Chor' },
          { type: CardType.VERB, value: 'erzählen' },
          { type: CardType.NOUN, value: 'Geburt' },
          { type: CardType.VERB, value: 'kommen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'groß' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'raus' },
        ],
      },
      {
        id: 2,
        title: 'S01E01 p2',
        cards: [
          { type: CardType.CONJUNCTION, value: 'wo' },
          { type: CardType.NOUN, value: 'Bienenstock' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'was' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'nein' },
          { type: CardType.VERB, value: 'helfen' },
          { type: CardType.VERB, value: 'gähnen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'nett' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'erneut' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'so' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'viele' },
          { type: CardType.NOUN, value: 'Frage' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'hier' },
          { type: CardType.VERB, value: 'bitten' },
          { type: CardType.VERB, value: 'essen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'erst' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'einmal' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'lecker' },
          { type: CardType.NOUN, value: 'Essen' },
          { type: CardType.NOUN, value: 'Nektar' },
          { type: CardType.NOUN, value: 'Frau' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'willkommen' },
          { type: CardType.NOUN, value: 'Schnarchen' },
          { type: CardType.VERB, value: 'kichern', hidden: true },
          { type: CardType.ADJECTIVE_ADVERB, value: 'jetzt' },
          { type: CardType.PREPOSITION, value: 'auf' },
          { type: CardType.NOUN, value: 'Königin' },
          { type: CardType.NOUN, value: 'Name' },
          { type: CardType.VERB, value: 'geben' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'danach' },
          { type: CardType.VERB, value: 'beginnen' },
          { type: CardType.NOUN, value: 'Unterricht' },
        ],
      },
      {
        id: 3,
        title: 'S01E01 p3',
        cards: [
          { type: CardType.NOUN, value: 'Hunger' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'süß' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'saftig', hidden: true },
          { type: CardType.VERB, value: 'träumen' },
          { type: CardType.VERB, value: 'probieren' },
          { type: CardType.VERB, value: 'malen' },
          { type: CardType.VERB, value: 'schnüffeln', hidden: true },
          { type: CardType.ADJECTIVE_ADVERB, value: 'ja' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'lustig' },
          { type: CardType.VERB, value: 'riechen' },
          { type: CardType.CONJUNCTION, value: 'aber' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'gut' },
          { type: CardType.CONJUNCTION, value: 'als' },
          { type: CardType.NOUN, value: 'Traum' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'also' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'daran' },
          { type: CardType.VERB, value: 'können' },
          { type: CardType.VERB, value: 'gewöhnen' },
          { type: CardType.VERB, value: 'wünschen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'letzte' },
          { type: CardType.NOUN, value: 'Güte' },
          { type: CardType.VERB, value: 'sehen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'schön' },
          { type: CardType.PREPOSITION, value: 'aus' },
          { type: CardType.VERB, value: 'dastehen' },
          { type: CardType.VERB, value: 'stecken' },
          { type: CardType.VERB, value: 'müssen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'immer' },
          { type: CardType.NOUN, value: 'Gruppe' },
          { type: CardType.VERB, value: 'bleiben' },
          { type: CardType.CONJUNCTION, value: 'denn' },
        ],
      },
      {
        id: 4,
        title: 'S01E01 p4',
        cards: [
          { type: CardType.PHRASE, value: 'Hallo' },
          { type: CardType.VERB, value: 'heißen' },
          { type: CardType.VERB, value: 'finden' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'auch' },
          { type: CardType.VERB, value: 'haben' },
          { type: CardType.NOUN, value: 'Ei' },
          { type: CardType.VERB, value: 'legen' },
          { type: CardType.VERB, value: 'schlüpfen', hidden: true },
          { type: CardType.ADJECTIVE_ADVERB, value: 'verschieden' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'sogar' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'besonders' },
          { type: CardType.VERB, value: 'scheinen' },
          { type: CardType.VERB, value: 'schmatzen', hidden: true },
          { type: CardType.CONJUNCTION, value: 'wie' },
          { type: CardType.PHRASE, value: 'Na' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'dann' },
          { type: CardType.PREPOSITION, value: 'an' },
          { type: CardType.VERB, value: 'schlafen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'gemeinsam' },
          { type: CardType.VERB, value: 'arbeiten' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'geschäftig' },
          { type: CardType.NOUN, value: 'Summe' },
          { type: CardType.VERB, value: 'dürfen' },
          { type: CardType.PREPOSITION, value: 'durch' },
          { type: CardType.NOUN, value: 'Bitte' },
          { type: CardType.VERB, value: 'danken' },
          { type: CardType.VERB, value: 'weitergehen' },
          { type: CardType.NOUN, value: 'Wiese', hidden: true },
          { type: CardType.ADJECTIVE_ADVERB, value: 'draußen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'hell' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'warm' },
        ],
      },
      {
        id: 5,
        title: 'S01E01 p5',
        cards: [
          { type: CardType.NOUN, value: 'Sonne' },
          { type: CardType.VERB, value: 'wollen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'wohl' },
          { type: CardType.VERB, value: 'wissen' },
          { type: CardType.VERB, value: 'machen' },
          { type: CardType.NOUN, value: 'Achtung' },
          { type: CardType.CONJUNCTION, value: 'co-noch' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'viel' },
          { type: CardType.NOUN, value: 'Nachschub' },
          { type: CardType.NOUN, value: 'Vorsicht' },
          { type: CardType.NOUN, value: 'Macht' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'anderer' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'damit' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'toll' },
          { type: CardType.VERB, value: 'spielen' },
          { type: CardType.PREPOSITION, value: 'um' },
          { type: CardType.PREPOSITION, value: 'pre-zu' },
          { type: CardType.NOUN, value: 'Müdigkeit' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'schnell' },
          { type: CardType.VERB, value: 'gehen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'heute' },
          { type: CardType.NOUN, value: 'Morgen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'recht' },
          { type: CardType.NOUN, value: 'Mal' },
          { type: CardType.NOUN, value: 'Gemurmel' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'fertig' },
          { type: CardType.NOUN, value: 'Gut' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'genau' },
          { type: CardType.NOUN, value: 'Form' },
          { type: CardType.NOUN, value: 'Größe' },
          { type: CardType.VERB, value: 'stimmen' },
        ],
      },
      {
        id: 6,
        title: 'S01E01 p6',
        cards: [
          { type: CardType.PREPOSITION, value: 'bei' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'doch' },
          { type: CardType.CONJUNCTION, value: 'oder' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'ad-schon' },
          { type: CardType.NOUN, value: 'Blume' },
          { type: CardType.VERB, value: 'bauen' },
          { type: CardType.NOUN, value: 'Wabe' },
          { type: CardType.VERB, value: 'ausgleichen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'wann' },
          { type: CardType.PREPOSITION, value: 'nach' },
          { type: CardType.CONJUNCTION, value: 'wenn' },
          { type: CardType.VERB, value: 'kitzeln' },
          { type: CardType.NOUN, value: 'Nase' },
          { type: CardType.VERB, value: 'fliegen' },
          { type: CardType.VERB, value: 'bestimmen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'schwer' },
          { type: CardType.NOUN, value: 'Angst' },
          { type: CardType.VERB, value: 'trauen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'nur' },
          { type: CardType.NOUN, value: 'Flügel' },
          { type: CardType.NOUN, value: 'Position' },
          { type: CardType.VERB, value: 'bewegen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'ganz' },
          { type: CardType.VERB, value: 'abschließen' },
          { type: CardType.NOUN, value: 'Luft' },
          { type: CardType.CONJUNCTION, value: 'dass' },
          { type: CardType.VERB, value: 'halten' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'ruhig' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'jeder' },
          { type: CardType.PHRASE, value: 'Ach' },
          { type: CardType.NOUN, value: 'Leben' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'gemütlich' },
          { type: CardType.VERB, value: 'anfangen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'hoch' },
          { type: CardType.VERB, value: 'gehören' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'wirklich' },
        ],
      },
      {
        id: 7,
        title: 'S01E01 p7',
        cards: [
          { type: CardType.NOUN, value: 'Ordnung' },
          { type: CardType.PREPOSITION, value: 'mit' },
          { type: CardType.VERB, value: 'tun' },
          { type: CardType.VERB, value: 'wehen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'eigentlich' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'nah' },
          { type: CardType.VERB, value: 'klappen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'endlich' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'super' },
          { type: CardType.VERB, value: 'duften' },
          { type: CardType.VERB, value: 'summen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'überall' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'vielleicht' },
          { type: CardType.VERB, value: 'wiedersehen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'rein' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'lieber' },
          { type: CardType.VERB, value: 'zurückkommen' },
          { type: CardType.NOUN, value: 'Nickerchen' },
          { type: CardType.VERB, value: 'genießen' },
          { type: CardType.VERB, value: 'entdecken' },
          { type: CardType.VERB, value: 'reden' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'sauber' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'nützlich' },
          { type: CardType.NOUN, value: 'Schnecke' },
          { type: CardType.PHRASE, value: 'Los' },
          { type: CardType.NOUN, value: 'Stock' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'sonst' },
          { type: CardType.VERB, value: 'klauen' },
          { type: CardType.VERB, value: 'lachen' },
          { type: CardType.VERB, value: 'kennenlernen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'bunt' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'runter' },
          { type: CardType.NOUN, value: 'Häuschen' },
          { type: CardType.NOUN, value: 'Bank' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'drin' },
          { type: CardType.VERB, value: 'sitzen' },
        ],
      },
      {
        id: 8,
        title: 'S01E01 p8',
        cards: [
          { type: CardType.NOUN, value: 'Haus' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'dabei' },
          { type: CardType.NOUN, value: 'Gast' },
          { type: CardType.VERB, value: 'empfangen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'übrigens' },
          { type: CardType.VERB, value: 'aufhören' },
          { type: CardType.NOUN, value: 'Arm' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'verrückt' },
          { type: CardType.VERB, value: 'warten' },
          { type: CardType.VERB, value: 'suchen' },
          { type: CardType.VERB, value: 'gefallen' },
          { type: CardType.NOUN, value: 'Musik' },
          { type: CardType.VERB, value: 'klingen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'oben' },
          { type: CardType.NOUN, value: 'Regenbogen' },
          { type: CardType.NOUN, value: 'Geschichte' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'darüber' },
          { type: CardType.NOUN, value: 'Mutter' },
          { type: CardType.NOUN, value: 'Vater' },
          { type: CardType.NOUN, value: 'Regen' },
          { type: CardType.VERB, value: 'sagen' },
          { type: CardType.VERB, value: 'sollen' },
          { type: CardType.VERB, value: 'wegfliegen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'gefährlich' },
          { type: CardType.VERB, value: 'leiden' },
        ],
      },
      {
        id: 9,
        title: 'S01E01 p9',
        cards: [
          { type: CardType.ADJECTIVE_ADVERB, value: 'alt' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'genug' },
          { type: CardType.NOUN, value: 'Tag' },
          { type: CardType.VERB, value: 'sammeln' },
          { type: CardType.NOUN, value: 'Sorge' },
          { type: CardType.VERB, value: 'freuen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'darauf' },
          { type: CardType.PREPOSITION, value: 'bis' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'wunderschön' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'lieb' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'dort' },
          { type: CardType.VERB, value: 'leben' },
          { type: CardType.NOUN, value: 'Gemeinschaft' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'nun' },
          { type: CardType.VERB, value: 'mögen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'hübsch' },
          { type: CardType.NOUN, value: 'Rücken' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'irgendwo' },
          { type: CardType.NOUN, value: 'Nacht' },
          { type: CardType.VERB, value: 'denken' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'davon' },
          { type: CardType.VERB, value: 'verlassen' },
          { type: CardType.VERB, value: 'schnarchen' },
        ],
      },
    ],
  },
  {
    id: 7,
    title: 'Goethe',
    lessons: [
      {
        id: 1,
        title: '4.1',
        cards: [
          { type: CardType.NOUN, value: 'Sprachschule' },
          { type: CardType.NOUN, value: 'Hausarbeit' },
          { type: CardType.NOUN, value: 'Kindergarten' },
          { type: CardType.NOUN, value: 'Sprachkurs' },
          { type: CardType.VERB, value: 'mithelfen' },
          { type: CardType.VERB, value: 'losgehen' },
          { type: CardType.CONJUNCTION, value: 'denn' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'ideal' },
          { type: CardType.PREPOSITION, value: 'pre-gegen' },
          { type: CardType.PHRASE, value: 'frei haben' },
          { type: CardType.NOUN, value: 'Flug' },
          { type: CardType.NOUN, value: 'Ferien' },
          { type: CardType.NOUN, value: 'Kultur' },
          { type: CardType.NOUN, value: 'Kinderbetreuung' },
          { type: CardType.VERB, value: 'umsteigen' },
          { type: CardType.VERB, value: 'abreisen' },
          { type: CardType.CONJUNCTION, value: 'dass' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'erwachsen' },
          { type: CardType.PHRASE, value: 'Australien' },
          { type: CardType.NOUN, value: 'Enkelkind' },
          { type: CardType.NOUN, value: 'Lebenserfahrung' },
          { type: CardType.NOUN, value: 'USA' },
          { type: CardType.NOUN, value: 'Möglichkeit' },
          { type: CardType.VERB, value: 'mitarbeiten' },
          { type: CardType.VERB, value: 'zurückfliegen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'zu Ende' },
          { type: CardType.PHRASE, value: 'Malaysia' },
          { type: CardType.NOUN, value: 'Bericht' },
        ],
      },
      {
        id: 2,
        title: '4.2',
        cards: [
          { type: CardType.NOUN, value: 'Projekt' },
          { type: CardType.NOUN, value: 'Kenntnis' },
          { type: CardType.NOUN, value: 'Vorteil' },
          { type: CardType.VERB, value: 'bewerben' },
          { type: CardType.VERB, value: 'verbringen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'traurig' },
          { type: CardType.PHRASE, value: '(sich) sicher sein' },
          { type: CardType.NOUN, value: 'Nachteil' },
          { type: CardType.NOUN, value: 'Auszubildende' },
          { type: CardType.NOUN, value: 'Bezahlung' },
          { type: CardType.NOUN, value: 'Gehalt' },
          { type: CardType.VERB, value: 'betreuen' },
          { type: CardType.VERB, value: 'erreichen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'sozial' },
          { type: CardType.PHRASE, value: 'Kanada' },
          { type: CardType.NOUN, value: 'Farm' },
          { type: CardType.NOUN, value: 'Taschengeld' },
          { type: CardType.NOUN, value: 'Agentur' },
          { type: CardType.NOUN, value: 'Besucher' },
          { type: CardType.VERB, value: 'lassen' },
          { type: CardType.VERB, value: 'wünschen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'absolut' },
          { type: CardType.PHRASE, value: 'Norwegen' },
          { type: CardType.NOUN, value: 'Messe' },
          { type: CardType.NOUN, value: 'Zustellbett' },
          { type: CardType.NOUN, value: 'Safe' },
          { type: CardType.NOUN, value: 'Schreibtisch' },
          { type: CardType.VERB, value: 'anreisen' },
        ],
      },
      {
        id: 3,
        title: '4.3',
        cards: [
          { type: CardType.VERB, value: 'bestätigen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'eventuell' },
          { type: CardType.PHRASE, value: 'England' },
          { type: CardType.NOUN, value: 'Duschbad' },
          { type: CardType.NOUN, value: 'WC' },
          { type: CardType.NOUN, value: 'Klimaanlage' },
          { type: CardType.NOUN, value: 'Minibar' },
          { type: CardType.VERB, value: 'übernachten' },
          { type: CardType.VERB, value: 'ausfüllen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'reichhaltig' },
          { type: CardType.PHRASE, value: 'Argentinien' },
          { type: CardType.NOUN, value: 'Snack' },
          { type: CardType.NOUN, value: 'Gepäckraum' },
          { type: CardType.NOUN, value: 'Parkplatz' },
          { type: CardType.NOUN, value: 'Parkhaus' },
          { type: CardType.VERB, value: 'tragen' },
          { type: CardType.VERB, value: 'bedanken' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'täglich' },
          { type: CardType.PHRASE, value: 'Italien' },
          { type: CardType.NOUN, value: 'Preisliste' },
          { type: CardType.NOUN, value: 'Viertelstunde' },
          { type: CardType.NOUN, value: 'WLAN' },
          { type: CardType.NOUN, value: 'Anfrage' },
          { type: CardType.VERB, value: 'nennen' },
          { type: CardType.VERB, value: 'antippen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'ausgebucht' },
          { type: CardType.PHRASE, value: 'das 5-Sterne-Hotel' },
        ],
      },
      {
        id: 4,
        title: '4.4',
        cards: [
          { type: CardType.NOUN, value: 'Zimmerreservierung' },
          { type: CardType.NOUN, value: 'Reservierung' },
          { type: CardType.NOUN, value: 'Anreise' },
          { type: CardType.NOUN, value: 'Abreise' },
          { type: CardType.VERB, value: 'couchsurfen' },
          { type: CardType.VERB, value: 'absagen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'hiermit' },
          { type: CardType.PHRASE, value: 'Bescheid geben' },
          { type: CardType.NOUN, value: 'Übernachtung' },
          { type: CardType.NOUN, value: 'Raucherzimmer' },
          { type: CardType.NOUN, value: 'Augenblick' },
          { type: CardType.NOUN, value: 'Reisepass' },
          { type: CardType.VERB, value: 'ärgern' },
          { type: CardType.VERB, value: 'lohnen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'im Voraus' },
          { type: CardType.PHRASE, value: 'Sehr geehrte' },
          { type: CardType.NOUN, value: 'Rezeptionist' },
          { type: CardType.NOUN, value: 'Pizzeria' },
          { type: CardType.NOUN, value: 'Gericht' },
          { type: CardType.NOUN, value: 'Weg' },
          { type: CardType.VERB, value: 'buchen' },
          { type: CardType.VERB, value: 'verreisen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'extra' },
          { type: CardType.PHRASE, value: 'die 3-Tagekarte' },
          { type: CardType.NOUN, value: 'Fahrkarte' },
          { type: CardType.NOUN, value: 'Tram' },
          { type: CardType.NOUN, value: 'Verkehrsverbund' },
        ],
      },
      {
        id: 5,
        title: '4.5',
        cards: [
          { type: CardType.NOUN, value: 'Einzelfahrschein' },
          { type: CardType.VERB, value: 'zurückkommen' },
          { type: CardType.VERB, value: 'einigen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'überall' },
          { type: CardType.PHRASE, value: 'Tschechien' },
          { type: CardType.NOUN, value: 'Wochenkarte' },
          { type: CardType.NOUN, value: 'Monatskarte' },
          { type: CardType.NOUN, value: 'Gesamtpreis' },
          { type: CardType.NOUN, value: 'Bildschirm' },
          { type: CardType.VERB, value: 'engagieren' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'gut' },
          { type: CardType.PHRASE, value: 'Tschechisch' },
          { type: CardType.NOUN, value: 'Banknote' },
          { type: CardType.NOUN, value: 'Fahrgast' },
          { type: CardType.NOUN, value: 'Host' },
          { type: CardType.NOUN, value: 'Tipp' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'ungefähr' },
          { type: CardType.PHRASE, value: 'Österreich' },
          { type: CardType.NOUN, value: 'Glück' },
          { type: CardType.NOUN, value: 'Fan' },
          { type: CardType.NOUN, value: 'Hostel' },
          { type: CardType.NOUN, value: 'Privatperson' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'deshalb' },
          { type: CardType.PHRASE, value: 'die Gasteltern' },
          { type: CardType.NOUN, value: 'Schlafplatz' },
          { type: CardType.NOUN, value: 'Couch' },
          { type: CardType.NOUN, value: 'Geschenk' },
        ],
      },
      {
        id: 6,
        title: '4.6',
        cards: [
          { type: CardType.NOUN, value: 'Pech' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'perfekt' },
          { type: CardType.NOUN, value: 'Profil' },
          { type: CardType.NOUN, value: 'Workshop' },
          { type: CardType.NOUN, value: 'Absage' },
          { type: CardType.NOUN, value: 'Nachricht' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'bequem' },
          { type: CardType.NOUN, value: 'Dom' },
          { type: CardType.NOUN, value: 'Boden' },
          { type: CardType.NOUN, value: 'Festival' },
          { type: CardType.NOUN, value: 'Berg' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'eben' },
          { type: CardType.NOUN, value: 'Ort' },
          { type: CardType.NOUN, value: 'Entspannung' },
          { type: CardType.NOUN, value: 'Camping' },
          { type: CardType.NOUN, value: 'Wohnmobil' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'chaotisch' },
          { type: CardType.NOUN, value: 'Musik' },
          { type: CardType.NOUN, value: 'Haustausch' },
          { type: CardType.NOUN, value: 'Fernseher' },
          { type: CardType.NOUN, value: 'Link' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'pur' },
          { type: CardType.NOUN, value: 'Visum' },
          { type: CardType.NOUN, value: 'Verb' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'dunkel' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'wunderschön' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'schmutzig' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'zurück' },
        ],
      },
      {
        id: 7,
        title: '5.1',
        cards: [
          { type: CardType.NOUN, value: 'Nebenkosten' },
          { type: CardType.NOUN, value: 'Heizung' },
          { type: CardType.NOUN, value: 'Wohnbereich' },
          { type: CardType.NOUN, value: 'Objekt' },
          { type: CardType.NOUN, value: 'Müllabfuhr' },
          { type: CardType.NOUN, value: 'Warmmiete' },
          { type: CardType.NOUN, value: 'Single' },
          { type: CardType.NOUN, value: 'Einfamilienhaus' },
          { type: CardType.VERB, value: 'bieten' },
          { type: CardType.VERB, value: 'renovieren' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'entfernt' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'dringend' },
          { type: CardType.PHRASE, value: 'mitten in' },
          { type: CardType.PHRASE, value: 'Herzliche Grüße' },
          { type: CardType.NOUN, value: 'Kaltmiete' },
          { type: CardType.NOUN, value: 'Wohngemeinschaft' },
          { type: CardType.NOUN, value: 'Innenhof' },
          { type: CardType.NOUN, value: 'Stockwerk' },
          { type: CardType.NOUN, value: 'Tiefgarage' },
          { type: CardType.NOUN, value: 'Garage' },
          { type: CardType.NOUN, value: 'Flur' },
          { type: CardType.NOUN, value: 'Dach' },
          { type: CardType.VERB, value: 'vermieten' },
          { type: CardType.VERB, value: 'ansehen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'maximal' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'modern' },
          { type: CardType.PHRASE, value: 'danke schön' },
          { type: CardType.PHRASE, value: 'verfügen über' },
          { type: CardType.NOUN, value: 'Altbauwohnung' },
          { type: CardType.NOUN, value: 'Decke' },
        ],
      },
      {
        id: 8,
        title: '5.2',
        cards: [
          { type: CardType.NOUN, value: 'Kinderwagen' },
          { type: CardType.NOUN, value: 'Schlafzimmer' },
          { type: CardType.NOUN, value: 'Monatsmiete' },
          { type: CardType.NOUN, value: 'Badewanne' },
          { type: CardType.NOUN, value: 'Abstellraum' },
          { type: CardType.NOUN, value: 'Highlight' },
          { type: CardType.VERB, value: 'betragen' },
          { type: CardType.VERB, value: 'relaxen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'italienisch' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'komisch' },
          { type: CardType.PHRASE, value: 'spazieren gehen' },
          { type: CardType.PHRASE, value: 'rausbringen' },
          { type: CardType.NOUN, value: 'Dachwohnung' },
          { type: CardType.NOUN, value: 'Dachterrasse' },
          { type: CardType.NOUN, value: 'Stadtpark' },
          { type: CardType.NOUN, value: 'Licht' },
          { type: CardType.NOUN, value: 'Lage' },
          { type: CardType.NOUN, value: 'Insel' },
          { type: CardType.NOUN, value: 'Stadtmensch' },
          { type: CardType.NOUN, value: 'Zentrum' },
          { type: CardType.VERB, value: 'klingen' },
          { type: CardType.VERB, value: 'gießen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'unpraktisch' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'zentral' },
          { type: CardType.PHRASE, value: 'mitfeiern' },
          { type: CardType.PHRASE, value: 'weitersagen' },
          { type: CardType.NOUN, value: 'Mitte' },
          { type: CardType.NOUN, value: 'Neuigkeit' },
          { type: CardType.NOUN, value: 'Architekt' },
          { type: CardType.NOUN, value: 'Surfbrett' },
        ],
      },
      {
        id: 9,
        title: '5.3',
        cards: [
          { type: CardType.NOUN, value: 'Treppe' },
          { type: CardType.NOUN, value: 'Klingel' },
          { type: CardType.NOUN, value: 'Ausblick' },
          { type: CardType.NOUN, value: 'Badezimmer' },
          { type: CardType.VERB, value: 'gehören' },
          { type: CardType.VERB, value: 'putzen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'praktisch' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'öfter' },
          { type: CardType.PHRASE, value: 'die Hochzeitspläne' },
          { type: CardType.PHRASE, value: 'die Treppenreinigung' },
          { type: CardType.NOUN, value: 'Eingangstür' },
          { type: CardType.NOUN, value: 'Wohnungstür' },
          { type: CardType.NOUN, value: 'Nachbar' },
          { type: CardType.NOUN, value: 'Erdgeschoss' },
          { type: CardType.NOUN, value: 'Spielsachen' },
          { type: CardType.NOUN, value: 'Lampe' },
          { type: CardType.NOUN, value: 'Supermarkt' },
          { type: CardType.NOUN, value: 'Arbeitszimmer' },
          { type: CardType.VERB, value: 'losfahren' },
          { type: CardType.VERB, value: 'abschließen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'dorthin' },
          { type: CardType.PREPOSITION, value: 'pre-zu' },
          { type: CardType.PHRASE, value: 'die Hofreinigung' },
          { type: CardType.PHRASE, value: 'der Essbereich' },
          { type: CardType.NOUN, value: 'Katze' },
          { type: CardType.NOUN, value: 'Tonne' },
          { type: CardType.NOUN, value: 'Paketdienst' },
          { type: CardType.NOUN, value: 'Dachgeschoss' },
          { type: CardType.NOUN, value: 'Pflanze' },
        ],
      },
      {
        id: 10,
        title: '5.4',
        cards: [
          { type: CardType.NOUN, value: 'Haustür' },
          { type: CardType.NOUN, value: 'Briefkasten' },
          { type: CardType.NOUN, value: 'Hausboot' },
          { type: CardType.VERB, value: 'informieren' },
          { type: CardType.VERB, value: 'beachten' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'gegenüber' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'süß' },
          { type: CardType.PHRASE, value: 'der Kochbereich' },
          { type: CardType.PHRASE, value: 'der Gymnastikkurs' },
          { type: CardType.NOUN, value: 'Tür' },
          { type: CardType.NOUN, value: 'Einweihungsparty' },
          { type: CardType.NOUN, value: 'Vermieter' },
          { type: CardType.NOUN, value: 'Kellerabteil' },
          { type: CardType.NOUN, value: 'Änderung' },
          { type: CardType.NOUN, value: 'Reparatur' },
          { type: CardType.NOUN, value: 'Müll' },
          { type: CardType.NOUN, value: 'Snowboard' },
          { type: CardType.VERB, value: 'ausschalten' },
          { type: CardType.VERB, value: 'vorbeikommen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'vorgestern' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'offen' },
          { type: CardType.PHRASE, value: 'das Mehrgenerationenhaus' },
          { type: CardType.PHRASE, value: 'das/der Yoga' },
          { type: CardType.NOUN, value: 'Anlage' },
          { type: CardType.NOUN, value: 'Liste' },
          { type: CardType.NOUN, value: 'Biomüll' },
          { type: CardType.NOUN, value: 'Paket' },
          { type: CardType.NOUN, value: 'Großküche' },
          { type: CardType.NOUN, value: 'Bibliothek' },
        ],
      },
      {
        id: 11,
        title: '5.5',
        cards: [
          { type: CardType.NOUN, value: 'Vormittag' },
          { type: CardType.NOUN, value: 'Treppenhaus' },
          { type: CardType.VERB, value: 'zumachen' },
          { type: CardType.VERB, value: 'teilen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'gesamt' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'damals' },
          { type: CardType.NOUN, value: 'Nutzung' },
          { type: CardType.NOUN, value: 'Lösung' },
          { type: CardType.NOUN, value: 'Hof' },
          { type: CardType.NOUN, value: 'Knie' },
          { type: CardType.NOUN, value: 'Langeweile' },
          { type: CardType.NOUN, value: 'Gemeinschaft' },
          { type: CardType.NOUN, value: 'Hausbewohner' },
          { type: CardType.NOUN, value: 'Verständnis' },
          { type: CardType.VERB, value: 'sparen' },
          { type: CardType.VERB, value: 'passen' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'miteinander' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'beliebt' },
          { type: CardType.NOUN, value: 'Großstadt' },
          { type: CardType.NOUN, value: 'Ordnung' },
          { type: CardType.NOUN, value: 'Mieter' },
          { type: CardType.NOUN, value: 'Zusammenleben' },
          { type: CardType.NOUN, value: 'Geige' },
          { type: CardType.NOUN, value: 'Sauberkeit' },
          { type: CardType.NOUN, value: 'Wochentag' },
          { type: CardType.NOUN, value: 'Wand' },
          { type: CardType.VERB, value: 'faxen' },
          { type: CardType.VERB, value: 'füttern' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'berufstätig' },
        ],
      },
      {
        id: 12,
        title: '5.6',
        cards: [
          { type: CardType.ADJECTIVE_ADVERB, value: 'zueinander' },
          { type: CardType.NOUN, value: 'Bahn' },
          { type: CardType.NOUN, value: 'Frühjahrsputz' },
          { type: CardType.NOUN, value: 'Interesse' },
          { type: CardType.NOUN, value: 'Quadratmeter' },
          { type: CardType.NOUN, value: 'Stil' },
          { type: CardType.NOUN, value: 'Gemeinschaftsraum' },
          { type: CardType.NOUN, value: 'Altersheim' },
          { type: CardType.NOUN, value: 'Veranstaltungsraum' },
          { type: CardType.VERB, value: 'kümmern' },
          { type: CardType.VERB, value: 'liefern' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'entspannt' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'offen' },
          { type: CardType.NOUN, value: 'Tier' },
          { type: CardType.NOUN, value: 'Physiotherapeut' },
          { type: CardType.NOUN, value: 'Instrument' },
          { type: CardType.NOUN, value: 'Grund' },
          { type: CardType.NOUN, value: 'Haustier' },
          { type: CardType.NOUN, value: 'Senior' },
          { type: CardType.NOUN, value: 'Nichtraucher' },
          { type: CardType.NOUN, value: 'Putzplan' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'kompliziert' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'ordentlich' },
          { type: CardType.NOUN, value: 'Kleiderschrank' },
          { type: CardType.NOUN, value: 'Kopfhörer' },
          { type: CardType.NOUN, value: 'Spieleabend' },
          { type: CardType.NOUN, value: 'Zoo' },
          { type: CardType.ADJECTIVE_ADVERB, value: 'gegenseitig' },
        ],
      },
    ],
  },
];

/* console.log(
  'jjjj',
  (courses.find((e) => e.id === 7)?.lessons.find((e) => e.id === 1)?.cards || []).length,
  shuffleArrayByType(courses.find((e) => e.id === 7)?.lessons.find((e) => e.id === 1)?.cards || [], 1),
);

console.log(
  'kkk',
  chunkArray(courses.find((e) => e.id === 7)?.lessons.find((e) => e.id === 1)?.cards || [], 30).map((cards, i) => ({
    id: i + 1,
    title: `4.${i + 1}`,
    cards,
  })),
);
 */
