import { Article, CardType, Case, NounGender, NounNumber } from './types';

export const articles: Article[] = [
  {
    type: CardType.ARTICLE,
    value: 'der',
    translation: 'the',
    gender: NounGender.Maskulinum,
    number: NounNumber.singular,
    isDefinite: true,
    variants: [
      { case: Case.Nominativ, value: 'der' },
      { case: Case.Akkusativ, value: 'den' },
      { case: Case.Dativ, value: 'dem' },
      { case: Case.Genitiv, value: 'des' },
    ],
  },
  {
    type: CardType.ARTICLE,
    value: 'die',
    uniqueValue: 'dieF',
    translation: 'the',
    gender: NounGender.Femininum,
    number: NounNumber.singular,
    isDefinite: true,
    variants: [
      { case: Case.Nominativ, value: 'die' },
      { case: Case.Akkusativ, value: 'die' },
      { case: Case.Dativ, value: 'der' },
      { case: Case.Genitiv, value: 'der' },
    ],
  },
  {
    type: CardType.ARTICLE,
    value: 'das',
    translation: 'the',
    gender: NounGender.Neutrum,
    number: NounNumber.singular,
    isDefinite: true,
    variants: [
      { case: Case.Nominativ, value: 'das' },
      { case: Case.Akkusativ, value: 'das' },
      { case: Case.Dativ, value: 'dem' },
      { case: Case.Genitiv, value: 'des' },
    ],
  },
  {
    type: CardType.ARTICLE,
    value: 'die',
    uniqueValue: 'dieP',
    translation: 'the',
    gender: NounGender.Plural,
    number: NounNumber.plural,
    isDefinite: true,
    variants: [
      { case: Case.Nominativ, value: 'die' },
      { case: Case.Akkusativ, value: 'die' },
      { case: Case.Dativ, value: 'den' },
      { case: Case.Genitiv, value: 'der' },
    ],
  },
  {
    type: CardType.ARTICLE,
    value: 'ein',
    translation: 'a',
    gender: NounGender.Maskulinum,
    number: NounNumber.singular,
    isDefinite: false,
    variants: [
      { case: Case.Nominativ, value: 'ein' },
      { case: Case.Akkusativ, value: 'einen' },
      { case: Case.Dativ, value: 'einem' },
      { case: Case.Genitiv, value: 'eines' },
    ],
  },
  {
    type: CardType.ARTICLE,
    value: 'eine',
    translation: 'a',
    gender: NounGender.Femininum,
    number: NounNumber.singular,
    isDefinite: false,
    variants: [
      { case: Case.Nominativ, value: 'eine' },
      { case: Case.Akkusativ, value: 'eine' },
      { case: Case.Dativ, value: 'einer' },
      { case: Case.Genitiv, value: 'einer' },
    ],
  },
  {
    type: CardType.ARTICLE,
    value: 'ein',
    translation: 'a',
    gender: NounGender.Neutrum,
    number: NounNumber.singular,
    isDefinite: false,
    variants: [
      { case: Case.Nominativ, value: 'ein' },
      { case: Case.Akkusativ, value: 'ein' },
      { case: Case.Dativ, value: 'einem' },
      { case: Case.Genitiv, value: 'eines' },
    ],
  },
];
