import type { Noun } from './types';
import { CardType, Case, NounGender, NounNumber } from './types';

export const nouns: Noun[] = [
  {
    type: CardType.NOUN,
    value: 'Jahr',
    translation: 'year',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Jahr' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Jahrs/Jahres' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Jahr' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Jahr' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Jahre' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Jahre' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Jahren' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Jahre' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Mal',
    translation: 'time',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Mal' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Mals/Males' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Mal' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Mal' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Male' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Male' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Malen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Male' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Beispiel',
    translation: 'example',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Beispiel' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Beispiels/Beispieles' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Beispiel' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Beispiel' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Beispiele' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Beispiele' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Beispielen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Beispiele' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Zeit',
    translation: 'time; period',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Zeit' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Zeit' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Zeit' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Zeit' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Zeiten' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Zeiten' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Zeiten' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Zeiten' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Frau',
    translation: 'wife; woman; Mrs.',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Frau' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Frau' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Frau' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Frau' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Frauen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Frauen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Frauen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Frauen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Mensch',
    translation: 'human; person; man',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Mensch' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Menschen' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Menschen' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Menschen' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Menschen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Menschen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Menschen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Menschen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Deutsch',
    translation: 'German (language)',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Deutsch' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Deutschs/Deutsch' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Deutsch' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Deutsch' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Kind',
    translation: 'child; kid',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Kind' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Kinds/Kindes' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Kind' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Kind' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Kinder' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Kinder' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Kindern' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Kinder' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Tag',
    translation: 'day',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Tag' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Tags/Tages' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Tag' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Tag' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Tage' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Tage' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Tagen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Tage' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Mann',
    translation: 'man; guy',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Mann' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Manns/Mannes' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Mann' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Mann' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Männer' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Männer' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Männern' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Männer' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Land',
    translation: 'country; ground; land',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Land' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Lands/Landes' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Land' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Land' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Länder' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Länder' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Ländern' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Länder' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Frage',
    translation: 'question; issue; matter',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Frage' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Frage' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Frage' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Frage' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Fragen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Fragen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Fragen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Fragen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Haus',
    translation: 'home; house',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Haus' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Hauses' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Haus' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Haus' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Häuser' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Häuser' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Häusern' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Häuser' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Fall',
    translation: 'drop; case',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Fall' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Falls/Falles' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Fall' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Fall' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Fälle' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Fälle' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Fällen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Fälle' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Leute',
    translation: 'people; folk',
    gender: NounGender.Plural,
    variants: [
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Leute' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Leute' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Leuten' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Leute' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Arbeit',
    translation: 'job; work; labor; chore; task',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Arbeit' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Arbeit' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Arbeit' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Arbeit' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Arbeiten' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Arbeiten' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Arbeiten' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Arbeiten' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Prozent',
    translation: 'percent',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Prozent' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Prozents/Prozentes' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Prozent' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Prozent' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Prozente' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Prozente' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Prozenten' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Prozente' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Hand',
    translation: 'hand',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Hand' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Hand' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Hand' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Hand' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Hände' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Hände' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Händen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Hände' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Stadt',
    translation: 'city',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Stadt' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Stadt' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Stadt' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Stadt' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Städte' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Städte' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Städten' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Städte' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Herr',
    translation: 'gentleman',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Herr' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Herrn/Herren' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Herren/Herrn' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Herren/Herrn' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Herren' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Herren' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Herren/Herrn' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Herren' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Teil',
    translation: 'part',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Teil' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Teils/Teiles' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Teil' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Teil' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Teile' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Teile' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Teilen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Teile' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Problem',
    translation: 'trouble',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Problem' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Problems' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Problem' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Problem' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Probleme' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Probleme' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Problemen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Probleme' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Welt',
    translation: 'world',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Welt' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Welt' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Welt' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Welt' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Welten' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Welten' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Welten' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Welten' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Recht',
    translation: 'law',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Recht' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Rechts/Rechtes' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Recht' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Recht' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Ende',
    translation: 'end',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Ende' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Endes' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Ende' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Ende' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Enden' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Enden' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Enden' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Enden' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Million',
    translation: 'million',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Million' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Million' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Million' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Million' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Millionen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Millionen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Millionen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Millionen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Schule',
    translation: 'school',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Schule' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Schule' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Schule' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Schule' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Schulen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Schulen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Schulen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Schulen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Woche',
    translation: 'week',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Woche' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Woche' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Woche' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Woche' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Wochen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Wochen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Wochen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Wochen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Vater',
    translation: 'father',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Vater' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Vaters' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Vater' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Vater' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Väter' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Väter' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Vätern' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Väter' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Seite',
    translation: 'page',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Seite' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Seite' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Seite' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Seite' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Seiten' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Seiten' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Seiten' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Seiten' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Leben',
    translation: 'life',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Leben' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Lebens' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Leben' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Leben' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Leben' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Leben' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Leben' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Leben' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Mutter',
    translation: 'mother',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Mutter' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Mutter' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Mutter' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Mutter' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Mütter' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Mütter' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Müttern' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Mütter' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Grund',
    translation: 'reason',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Grund' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Grunds/Grundes' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Grund' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Grund' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Gründe' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Gründe' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Gründen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Gründe' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Auge',
    translation: 'eye',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Auge' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Auges' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Auge' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Auge' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Augen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Augen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Augen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Augen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Wort',
    translation: 'word',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Wort' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Worts/Wortes' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Wort' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Wort' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Worte' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Worte' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Worten' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Worte' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Geld',
    translation: 'money',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Geld' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Gelds/Geldes' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Geld' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Geld' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Gelder' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Gelder' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Geldern' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Gelder' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Art',
    translation: 'kind',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Art' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Art' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Art' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Art' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Arten' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Arten' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Arten' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Arten' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Bereich',
    translation: 'area',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Bereich' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Bereichs/Bereiches' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Bereich' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Bereich' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Bereiche' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Bereiche' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Bereichen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Bereiche' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Weg',
    translation: 'path',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Weg' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Wegs/Weges' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Weg' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Weg' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Wege' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Wege' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Wegen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Wege' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Stunde',
    translation: 'hour',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Stunde' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Stunde' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Stunde' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Stunde' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Stunden' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Stunden' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Stunden' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Stunden' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Name',
    translation: 'name',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Name' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Namens' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Namen' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Namen' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Namen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Namen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Namen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Namen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Geschichte',
    translation: 'story',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Geschichte' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Geschichte' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Geschichte' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Geschichte' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Geschichten' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Geschichten' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Geschichten' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Geschichten' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Gesellschaft',
    translation: 'society',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Gesellschaft' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Gesellschaft' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Gesellschaft' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Gesellschaft' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Gesellschaften' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Gesellschaften' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Gesellschaften' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Gesellschaften' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Kopf',
    translation: 'head',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Kopf' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Kopfs/Kopfes' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Kopf' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Kopf' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Köpfe' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Köpfe' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Köpfen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Köpfe' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Paar',
    translation: 'pair',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Paar' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Paars/Paares' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Paar' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Paar' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Paare' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Paare' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Paaren' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Paare' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Möglichkeit',
    translation: 'facility',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Möglichkeit' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Möglichkeit' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Möglichkeit' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Möglichkeit' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Möglichkeiten' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Möglichkeiten' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Möglichkeiten' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Möglichkeiten' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Unternehmen',
    translation: 'venture',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Unternehmen' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Unternehmens' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Unternehmen' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Unternehmen' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Unternehmen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Unternehmen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Unternehmen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Unternehmen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Bild',
    translation: 'picture',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Bild' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Bilds/Bildes' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Bild' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Bild' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Bilder' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Bilder' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Bildern' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Bilder' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Buch',
    translation: 'book',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Buch' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Buchs/Buches' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Buch' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Buch' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Bücher' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Bücher' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Büchern' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Bücher' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Wasser',
    translation: 'water',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Wasser' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Wassers' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Wasser' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Wasser' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Wasser' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Wasser' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Wassern' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Wasser' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Stelle',
    translation: 'job',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Stelle' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Stelle' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Stelle' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Stelle' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Stellen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Stellen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Stellen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Stellen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Form',
    translation: 'form',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Form' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Form' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Form' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Form' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Formen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Formen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Formen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Formen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Entwicklung',
    translation: 'development',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Entwicklung' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Entwicklung' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Entwicklung' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Entwicklung' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Entwicklungen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Entwicklungen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Entwicklungen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Entwicklungen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Monat',
    translation: 'month',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Monat' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Monats/Monates' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Monat' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Monat' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Monate' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Monate' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Monaten' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Monate' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Familie',
    translation: 'family',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Familie' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Familie' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Familie' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Familie' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Familien' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Familien' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Familien' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Familien' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Morgen',
    translation: 'morning',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Morgen' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Morgens' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Morgen' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Morgen' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Morgen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Morgen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Morgen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Morgen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Abend',
    translation: 'evening',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Abend' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Abends' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Abend' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Abend' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Abende' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Abende' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Abenden' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Abende' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Aufgabe',
    translation: 'duty',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Aufgabe' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Aufgabe' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Aufgabe' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Aufgabe' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Aufgaben' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Aufgaben' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Aufgaben' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Aufgaben' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Universität',
    translation: 'university',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Universität' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Universität' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Universität' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Universität' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Universitäten' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Universitäten' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Universitäten' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Universitäten' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Sinn',
    translation: 'meaning',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Sinn' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Sinns/Sinnes' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Sinn' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Sinn' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Staat',
    translation: 'country',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Staat' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Staats/Staates' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Staat' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Staat' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Staaten' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Staaten' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Staaten' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Staaten' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Ziel',
    translation: 'destination',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Ziel' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Ziels/Zieles' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Ziel' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Ziel' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Ziele' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Ziele' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Zielen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Ziele' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Freund',
    translation: 'friend',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Freund' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Freunds/Freundes' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Freund' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Freund' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Freunde' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Freunde' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Freunden' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Freunde' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Thema',
    translation: 'issue',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Thema' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Themas' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Thema' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Thema' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Themen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Themen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Themen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Themen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Person',
    translation: 'person',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Person' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Person' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Person' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Person' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Personen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Personen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Personen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Personen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Euro',
    translation: 'euro',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Euro' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Euros/Euro' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Euro' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Euro' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Euros' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Euros' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Euros' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Euros' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Nacht',
    translation: 'night',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Nacht' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Nacht' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Nacht' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Nacht' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Nächte' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Nächte' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Nächten' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Nächte' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Ding',
    translation: 'thing',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Ding' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Dings/Dinges' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Ding' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Ding' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Dinge' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Dinge' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Dingen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Dinge' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Raum',
    translation: 'room',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Raum' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Raums/Raumes' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Raum' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Raum' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Räume' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Räume' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Räumen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Räume' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Blick',
    translation: 'view',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Blick' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Blicks/Blickes' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Blick' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Blick' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Blicke' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Blicke' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Blicken' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Blicke' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Platz',
    translation: 'place',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Platz' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Platzes' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Platz' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Platz' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Plätze' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Plätze' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Plätzen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Plätze' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Zahl',
    translation: 'number',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Zahl' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Zahl' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Zahl' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Zahl' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Zahlen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Zahlen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Zahlen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Zahlen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'System',
    translation: 'system',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'System' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Systems' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'System' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'System' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Systeme' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Systeme' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Systemen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Systeme' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Uhr',
    translation: 'clock',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Uhr' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Uhr' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Uhr' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Uhr' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Uhren' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Uhren' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Uhren' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Uhren' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Eltern',
    translation: 'parents',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Eltern' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Eltern' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Eltern' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Eltern' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Straße',
    translation: 'road',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Straße' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Straße' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Straße' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Straße' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Straßen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Straßen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Straßen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Straßen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Minute',
    translation: 'minute',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Minute' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Minute' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Minute' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Minute' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Minuten' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Minuten' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Minuten' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Minuten' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Gruppe',
    translation: 'group',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Gruppe' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Gruppe' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Gruppe' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Gruppe' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Gruppen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Gruppen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Gruppen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Gruppen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Wert',
    translation: 'value',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Wert' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Werts/Wertes' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Wert' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Wert' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Werte' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Werte' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Werten' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Werte' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Gesicht',
    translation: 'face',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Gesicht' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Gesichts' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Gesicht' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Gesicht' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Gesichter' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Gesichter' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Gesichtern' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Gesichter' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Sprache',
    translation: 'language',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Sprache' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Sprache' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Sprache' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Sprache' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Sprachen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Sprachen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Sprachen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Sprachen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Anfang',
    translation: 'start',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Anfang' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Anfangs/Anfanges' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Anfang' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Anfang' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Anfänge' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Anfänge' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Anfängen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Anfänge' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Ort',
    translation: 'place',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Ort' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Orts/Ortes' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Ort' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Ort' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Orte' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Orte' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Orten' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Orte' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Moment',
    translation: 'moment',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Moment' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Moments/Momentes' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Moment' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Moment' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Momente' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Momente' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Momenten' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Momente' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Folge',
    translation: 'order',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Folge' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Folge' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Folge' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Folge' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Folgen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Folgen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Folgen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Folgen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Interesse',
    translation: 'interest',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Interesse' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Interesses' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Interesse' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Interesse' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Interessen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Interessen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Interessen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Interessen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Milliarde',
    translation: 'billion',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Milliarde' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Milliarde' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Milliarde' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Milliarde' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Milliarden' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Milliarden' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Milliarden' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Milliarden' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Rolle',
    translation: 'role',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Rolle' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Rolle' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Rolle' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Rolle' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Rollen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Rollen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Rollen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Rollen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Tür',
    translation: 'door',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Tür' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Tür' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Tür' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Tür' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Türen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Türen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Türen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Türen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Schüler',
    translation: 'pupil',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Schüler' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Schülers' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Schüler' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Schüler' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Schüler' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Schüler' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Schülern' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Schüler' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Bedeutung',
    translation: 'meaning',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Bedeutung' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Bedeutung' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Bedeutung' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Bedeutung' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Bedeutungen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Bedeutungen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Bedeutungen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Bedeutungen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Text',
    translation: 'text',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Text' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Texts/Textes' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Text' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Text' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Texte' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Texte' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Texten' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Texte' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Ergebnis',
    translation: 'outcome',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Ergebnis' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Ergebnisses' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Ergebnis' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Ergebnis' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Ergebnisse' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Ergebnisse' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Ergebnissen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Ergebnisse' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Krieg',
    translation: 'war',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Krieg' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Kriegs/Krieges' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Krieg' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Krieg' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Kriege' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Kriege' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Kriegen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Kriege' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Weise',
    translation: 'manner',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Weise' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Weise' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Weise' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Weise' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Weisen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Weisen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Weisen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Weisen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Regierung',
    translation: 'government',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Regierung' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Regierung' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Regierung' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Regierung' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Regierungen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Regierungen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Regierungen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Regierungen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Stück',
    translation: 'piece',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Stück' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Stücks/Stückes' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Stück' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Stück' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Stücke' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Stücke' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Stücken' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Stücke' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Wohnung',
    translation: 'apartment',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Wohnung' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Wohnung' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Wohnung' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Wohnung' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Wohnungen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Wohnungen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Wohnungen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Wohnungen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Gespräch',
    translation: 'talk',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Gespräch' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Gesprächs/Gespräches' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Gespräch' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Gespräch' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Gespräche' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Gespräche' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Gesprächen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Gespräche' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Meter',
    translation: 'meter',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Meter' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Meters' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Meter' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Meter' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Meter' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Meter' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Metern' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Meter' },
    ],
  },
];
