import type { Noun } from './types';
import { CardType, Case, NounGender, NounNumber } from './types';

export const nouns: Noun[] = [
  {
    type: CardType.NOUN,
    value: 'Jahr',
    translation: 'year',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Jahr' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Jahrs/Jahres' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Jahr' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Jahr' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Jahre' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Jahre' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Jahren' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Jahre' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Mal',
    translation:
      'time; mark; marking - on person; print; monument; memorial; sign; brand; birthmark; base [SPORT]; touch [SPORT]; posts Pl. [SPORT]',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Mal' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Mals/Males' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Mal' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Mal' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Male' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Male' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Malen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Male' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Beispiel',
    translation: 'sample; paradigm; lead - initiative for others to follow; exemplar; lead [TECH.]',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Beispiel' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Beispiels/Beispieles' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Beispiel' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Beispiel' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Beispiele' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Beispiele' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Beispielen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Beispiele' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Zeit',
    translation: 'time; period; while; term; time duration; terms Pl.; tense [LING.]',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Zeit' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Zeit' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Zeit' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Zeit' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Zeiten' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Zeiten' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Zeiten' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Zeiten' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Frau',
    translation: 'wife; woman; female',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Frau' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Frau' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Frau' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Frau' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Frauen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Frauen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Frauen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Frauen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Mensch',
    translation: 'human; person; man; human being',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Mensch' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Menschen' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Menschen' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Menschen' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Menschen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Menschen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Menschen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Menschen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Deutsch',
    translation: 'German [LING.]',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Deutsch' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Deutschs/Deutsch' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Deutsch' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Deutsch' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Kind',
    translation: 'child; infant; kid [ugs.] - child; kiddy; moppet [ugs.]',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Kind' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Kinds/Kindes' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Kind' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Kind' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Kinder' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Kinder' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Kindern' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Kinder' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Tag',
    translation:
      'day; daytime; ground level [GEOL.]; ground surface [GEOL.]; day level; day surface; daylight; grass roots [TECH.]; land level [TECH.]; land surface [TECH.]; level ground [TECH.]; surface [TECH.]',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Tag' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Tags/Tages' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Tag' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Tag' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Tage' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Tage' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Tagen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Tage' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Mann',
    translation: 'man; husband; male; guy [ugs.]; hubby [ugs.]',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Mann' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Manns/Mannes' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Mann' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Mann' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Männer' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Männer' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Männern' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Männer' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Land',
    translation: 'Federal Land',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Land' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Lands/Landes' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Land' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Land' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Länder' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Länder' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Ländern' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Länder' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Frage',
    translation: 'question [LING.]; question; demand; issue; query',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Frage' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Frage' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Frage' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Frage' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Fragen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Fragen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Fragen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Fragen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Haus',
    translation: 'home; house; House auch: house - dynasty, family lineage; financial institution [FINAN.]; domicile',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Haus' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Hauses' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Haus' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Haus' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Häuser' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Häuser' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Häusern' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Häuser' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Fall',
    translation:
      'fall; case auch [JURA][LING.][MED.]; drop; instance; plunge; tumble; event; labefaction; slump; circumstance; decline; downstream; fall [GEOL.]; rake aft [NAUT.]',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Fall' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Falls/Falles' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Fall' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Fall' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Fälle' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Fälle' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Fällen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Fälle' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Prozent',
    translation: 'percentesp, per centesp,; percentage; per centum',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Prozent' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Prozents/Prozentes' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Prozent' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Prozent' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Prozente' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Prozente' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Prozenten' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Prozente' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Hand',
    translation: 'hand; manus [ANAT.]; pinion [ZOOL.]',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Hand' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Hand' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Hand' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Hand' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Hände' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Hände' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Händen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Hände' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Stadt',
    translation: 'city; town; burg [ugs.] (Amer.)',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Stadt' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Stadt' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Stadt' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Stadt' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Städte' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Städte' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Städten' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Städte' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Herr',
    translation: 'gentleman; master; sir; lord; gent; monsieur; mister; the Lord - God, Jesus Christ [REL.]',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Herr' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Herrn/Herren' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Herren/Herrn' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Herren/Herrn' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Herren' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Herren' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Herren/Herrn' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Herren' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Teil',
    translation: 'section; portion; fraction; proportion; partition; slice; tract; lot; cantle; chapter; fragment',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Teil' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Teils/Teiles' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Teil' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Teil' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Teile' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Teile' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Teilen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Teile' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Welt',
    translation: 'world; earth',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Welt' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Welt' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Welt' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Welt' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Welten' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Welten' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Welten' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Welten' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Ende',
    translation: 'ending; tail; cessation; conclusion',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Ende' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Endes' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Ende' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Ende' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Enden' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Enden' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Enden' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Enden' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Million',
    translation: 'million [Abk.: m]',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Million' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Million' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Million' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Million' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Millionen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Millionen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Millionen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Millionen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Schule',
    translation:
      'school; school - of fish, dolphins; school building; schoolhouse; pod - small herd or school of marine animals [ZOOL.]; alma mater [BILDUNGSW.]',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Schule' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Schule' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Schule' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Schule' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Schulen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Schulen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Schulen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Schulen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Woche',
    translation: 'week',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Woche' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Woche' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Woche' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Woche' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Wochen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Wochen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Wochen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Wochen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Vater',
    translation: 'father; begetter; master negative [TECH.]; master original [TECH.]; genitor selten [BIOL.]',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Vater' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Vaters' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Vater' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Vater' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Väter' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Väter' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Vätern' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Väter' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Seite',
    translation:
      'page; side; wing [TECH.]; side - opposing group; beam; aspect; point; hub page [COMP.]; flank; party; fold flank [GEOL.]; fold side [GEOL.]; fold limb [GEOL.]',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Seite' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Seite' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Seite' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Seite' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Seiten' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Seiten' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Seiten' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Seiten' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Mutter',
    translation: 'mother; nut [ING.]; screw nut [TECH.]; positive [TECH.]',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Mutter' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Mutter' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Mutter' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Mutter' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Mütter' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Mütter' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Müttern' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Mütter' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Grund',
    translation:
      'reason; cause; ground; occasion; bottom; matter - cause; base; basement; foundation; factor; motive for doing sth.; ground auch: grounds [fig.]; priming [TECH.]; first coat [TECH.]',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Grund' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Grunds/Grundes' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Grund' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Grund' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Gründe' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Gründe' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Gründen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Gründe' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Auge',
    translation:
      'eye [ANAT.]; pip - of a dice (Amer.); dot - of a dice; spot - of a dice (Amer.); boss [TECH.]; bud [BOT.]; lug [TECH.]; lift eye [TECH.]; wire eye [TECH.]; eye - of a potato [BOT.]; eye [TEXTIL.]; eyelet [TEXTIL.]',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Auge' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Auges' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Auge' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Auge' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Augen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Augen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Augen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Augen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Wort',
    translation: 'word; word [LING.]; vocable - a word esp. with regard to form rather than meaning [LING.]',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Wort' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Worts/Wortes' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Wort' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Wort' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Worte' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Worte' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Worten' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Worte' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Art',
    translation: 'sort; type; variety; species',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Art' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Art' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Art' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Art' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Arten' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Arten' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Arten' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Arten' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Bereich',
    translation:
      'area; scope; sector; zone; sphere; field; realm; district; division; block - of text; range [TECH.]; region [TECH.]; domain; reach',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Bereich' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Bereichs/Bereiches' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Bereich' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Bereich' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Bereiche' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Bereiche' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Bereichen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Bereiche' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Weg',
    translation:
      'path - way; way - road, distance; path [MATH.][TECH.]; route; alley; driveway; lane; road; track; channel; distance - distance covered; walk - path; means; pathway',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Weg' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Wegs/Weges' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Weg' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Weg' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Wege' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Wege' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Wegen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Wege' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Stunde',
    translation: 'hour; lesson; period - at school [BILDUNGSW.]; division',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Stunde' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Stunde' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Stunde' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Stunde' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Stunden' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Stunden' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Stunden' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Stunden' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Name',
    translation:
      'denomination; label; moniker auch: monicker [ugs.]; handle [ugs.] - given name; identifier - in software [TELEKOM.]',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Name' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Namens' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Namen' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Namen' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Namen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Namen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Namen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Namen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Geschichte',
    translation: 'story; tale; history - record of past events; narrative; saga',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Geschichte' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Geschichte' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Geschichte' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Geschichte' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Geschichten' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Geschichten' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Geschichten' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Geschichten' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Gesellschaft',
    translation:
      'society; company [KOMM.]; association; corporation [KOMM.]; fellowship - group of people sharing the same interests, brotherhood; party; community; organization,organisation, organization,; the public; body; function - social gathering',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Gesellschaft' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Gesellschaft' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Gesellschaft' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Gesellschaft' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Gesellschaften' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Gesellschaften' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Gesellschaften' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Gesellschaften' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Kopf',
    translation:
      'head [ANAT.][TECH.]; crown; owner; heading; conk hauptsächlich (Amer.) [ugs.]; mind [fig.] - intelligent person; header [TECH.]; brains used with sg. verb [sl.]; borehole top [TECH.]; collar [TECH.]; hole head [TECH.]; hole top [TECH.]; well mouth [TECH.]; well opening [TECH.]',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Kopf' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Kopfs/Kopfes' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Kopf' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Kopf' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Köpfe' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Köpfe' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Köpfen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Köpfe' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Paar',
    translation: 'pair; couple; brace; dyad; twosome; pair [ELEKT.][MATH.]',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Paar' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Paars/Paares' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Paar' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Paar' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Paare' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Paare' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Paaren' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Paare' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Möglichkeit',
    translation:
      'facility; possibility; potential; chance; eventuality; opportunity; contingency; potentiality; manageability; odds Pl.; alternative; way - method, manner; avenue [fig.]; feasibility',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Möglichkeit' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Möglichkeit' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Möglichkeit' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Möglichkeit' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Möglichkeiten' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Möglichkeiten' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Möglichkeiten' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Möglichkeiten' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Unternehmen',
    translation:
      'venture; corporation; establishment; enterprise [KOMM.]; company [KOMM.]; organization, [KOMM.]organisation, organization, [KOMM.]; undertaking; proposition; endeavor, endeavour,; task; unit; business company; corporate client; firm [KOMM.]',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Unternehmen' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Unternehmens' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Unternehmen' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Unternehmen' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Unternehmen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Unternehmen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Unternehmen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Unternehmen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Bild',
    translation:
      'picture; photograph [FOTO.]; image auch [MATH.][TECH.]; photo; drawing - picture, sketch; pattern; view; symbol; figure [TECH.]; prospect kein Pl. - mental picture; screen; illustration; likeness; tableau',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Bild' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Bilds/Bildes' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Bild' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Bild' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Bilder' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Bilder' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Bildern' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Bilder' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Buch',
    translation:
      'book; volume - book; casebook; quire - of paper; ledger [FINAN.]; page [fig.] - pages collectively selten',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Buch' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Buchs/Buches' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Buch' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Buch' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Bücher' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Bücher' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Büchern' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Bücher' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Stelle',
    translation:
      'job; place; position; post - job; spot; appointment; location; point; stead; situation; station; site; digit; engagement',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Stelle' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Stelle' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Stelle' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Stelle' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Stellen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Stellen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Stellen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Stellen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Form',
    translation:
      'form; shape; profile; mold, mould,; regime; mode; design; set form; style; mold, mould, [TECH.]; type [TECH.]; last [TECH.]',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Form' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Form' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Form' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Form' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Formen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Formen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Formen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Formen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Entwicklung',
    translation:
      'evolution; trend; processing [TECH.]; deployment; progress; design; progression; movement - change in attitude, behaviour; upgrowth; advancement; changes Pl.; design and development; formation',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Entwicklung' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Entwicklung' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Entwicklung' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Entwicklung' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Entwicklungen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Entwicklungen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Entwicklungen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Entwicklungen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Monat',
    translation: 'month',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Monat' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Monats/Monates' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Monat' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Monat' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Monate' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Monate' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Monaten' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Monate' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Familie',
    translation: 'family; kin; family - taxonomic category [BOT.]; clan [GEOL.]',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Familie' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Familie' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Familie' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Familie' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Familien' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Familien' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Familien' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Familien' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Morgen',
    translation: 'morning; morn [poet.]',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Morgen' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Morgens' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Morgen' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Morgen' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Morgen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Morgen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Morgen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Morgen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Abend',
    translation: 'evening; night; eve; weeknight',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Abend' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Abends' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Abend' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Abend' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Abende' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Abende' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Abenden' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Abende' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Aufgabe',
    translation:
      'duty; assignment; function; task; problem [MATH.]; job; mission; renunciation; challenge; responsibility; charging; exercise; renouncement; business',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Aufgabe' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Aufgabe' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Aufgabe' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Aufgabe' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Aufgaben' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Aufgaben' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Aufgaben' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Aufgaben' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Universität',
    translation: 'university; college [BILDUNGSW.] - university; alma mater [BILDUNGSW.]',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Universität' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Universität' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Universität' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Universität' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Universitäten' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Universitäten' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Universitäten' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Universitäten' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Staat',
    translation:
      'country; nation; state [POL.]; government; the Crown; general government [FINAN.]; body politic [POL.]; public sector [ADMIN.]',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Staat' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Staats/Staates' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Staat' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Staat' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Staaten' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Staaten' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Staaten' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Staaten' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Ziel',
    translation:
      'destination; goal; object; objective; target; aim; purpose; ambition; mark; end; intent; prompt; intention; finish - of a race or competition [SPORT]',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Ziel' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Ziels/Zieles' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Ziel' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Ziel' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Ziele' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Ziele' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Zielen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Ziele' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Freund',
    translation: 'boyfriend; beau',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Freund' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Freunds/Freundes' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Freund' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Freund' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Freunde' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Freunde' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Freunden' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Freunde' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Thema',
    translation: 'issue; subject; theme; topic; matter - subject; question; subject matter; subject [MUS.]',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Thema' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Themas' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Thema' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Thema' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Themen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Themen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Themen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Themen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Person',
    translation: 'person; character',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Person' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Person' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Person' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Person' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Personen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Personen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Personen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Personen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Ding',
    translation:
      'thing; object; gizmo (Amer.); item; entity; dingus; jigger (Amer.); doodad (Amer.) [ugs.]; caper; Thing auch: thing [HIST.]; thang (Amer.) [sl.]',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Ding' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Dings/Dinges' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Ding' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Ding' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Dinge' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Dinge' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Dingen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Dinge' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Blick',
    translation: 'look; sight; gaze; glance; vista; vision; sighting',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Blick' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Blicks/Blickes' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Blick' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Blick' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Blicke' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Blicke' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Blicken' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Blicke' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Zahl',
    translation:
      'number auch [MATH.]; figure [MATH.]; cipher (Amer.); numerary; digit; rate; count; numerical data [MATH.]',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Zahl' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Zahl' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Zahl' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Zahl' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Zahlen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Zahlen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Zahlen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Zahlen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'System',
    translation: 'system; scheme; order; regime auch: régime [POL.]; apparatus; crystal system [MIN.]',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'System' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Systems' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'System' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'System' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Systeme' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Systeme' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Systemen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Systeme' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Uhr',
    translation: 'clock; watch; timepiece; ticker',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Uhr' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Uhr' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Uhr' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Uhr' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Uhren' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Uhren' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Uhren' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Uhren' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Straße',
    translation: 'road; street; highway; way - road; forest road; avenue; strait [GEOG.]; route',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Straße' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Straße' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Straße' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Straße' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Straßen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Straßen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Straßen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Straßen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Minute',
    translation: 'minute [Abk.: min.]; original plot [TECH.]',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Minute' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Minute' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Minute' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Minute' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Minuten' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Minuten' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Minuten' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Minuten' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Gruppe',
    translation:
      'group; group [MATH.]; cluster; gang; squad auch [SPORT]; band used with sg. or pl. verb [MUS.]; assembly [TECH.]; bracket; category; denomination; passel; unit; class; clump',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Gruppe' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Gruppe' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Gruppe' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Gruppe' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Gruppen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Gruppen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Gruppen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Gruppen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Wert',
    translation:
      'value auch [FINAN.][MATH.][TECH.]; merit; worth; virtue - benefit; price; worthiness; magnitude; quality; caliber, calibre,; figure; score; account; data used with sg. or pl. verb; valuation',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Wert' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Werts/Wertes' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Wert' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Wert' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Werte' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Werte' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Werten' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Werte' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Gesicht',
    translation: 'face; pan [fig.] (Amer.) [sl.] - face; vision',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Gesicht' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Gesichts' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Gesicht' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Gesicht' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Gesichter' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Gesichter' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Gesichtern' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Gesichter' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Sprache',
    translation: 'language [COMP.][LING.]; tongue - language; lingo - foreign language [ugs.][hum.]',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Sprache' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Sprache' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Sprache' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Sprache' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Sprachen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Sprachen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Sprachen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Sprachen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Anfang',
    translation:
      'start; beginning; origin; initial; inception; commencement; onset; outset; incipience auch: incipiency; top; initiation; opening; proem; beginnings',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Anfang' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Anfangs/Anfanges' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Anfang' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Anfang' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Anfänge' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Anfänge' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Anfängen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Anfänge' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Ort',
    translation:
      'place; location; spot; scene - place where an incident occured; locality; city; site; venue; position; point [TECH.]; place [LING.]',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Ort' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Orts/Ortes' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Ort' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Ort' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Orte' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Orte' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Orten' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Orte' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Moment',
    translation: 'moment; instant',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Moment' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Moments/Momentes' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Moment' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Moment' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Momente' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Momente' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Momenten' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Momente' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Folge',
    translation:
      'order; consequence; sequence auch [MATH.]; series; result; suite; episode; succession; aftereffect auch: after-effect, after effect; aftermath; effect; implication; string; consecution',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Folge' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Folge' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Folge' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Folge' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Folgen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Folgen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Folgen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Folgen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Interesse',
    translation: 'interest; concern',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Interesse' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Interesses' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Interesse' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Interesse' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Interessen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Interessen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Interessen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Interessen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Milliarde',
    translation: 'billion [Abk.: bn] - thousand million',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Milliarde' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Milliarde' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Milliarde' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Milliarde' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Milliarden' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Milliarden' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Milliarden' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Milliarden' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Rolle',
    translation:
      'role [THEA.][SOZIOL.]; roll [TECH.]; part [CINE.][THEA.]; coil; pass; spool; bobbin; reel [TECH.]; roller [AVIAT.][ING.][TECH.]; pulley [TECH.]; castor [ING.]; sliding hole [TECH.]; aileron roll - aerobatic manoeuvre [AVIAT.]; bing hole - Derbyshire [MIN.]',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Rolle' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Rolle' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Rolle' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Rolle' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Rollen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Rollen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Rollen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Rollen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Tür',
    translation: 'door; doorway',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Tür' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Tür' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Tür' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Tür' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Türen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Türen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Türen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Türen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Schüler',
    translation: 'disciple; schoolboy',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Schüler' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Schülers' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Schüler' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Schüler' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Schüler' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Schüler' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Schülern' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Schüler' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Text',
    translation: 'text; copy - writing to be printed; words Pl.; lines Pl. [CINE.][THEA.]; lyrics [MUS.]',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Text' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Texts/Textes' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Text' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Text' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Texte' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Texte' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Texten' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Texte' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Ergebnis',
    translation:
      'outcome; result; finding; sum; conclusion; issue; upshot; count; effect; output; score; yield; achievement; performance',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Ergebnis' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Ergebnisses' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Ergebnis' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Ergebnis' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Ergebnisse' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Ergebnisse' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Ergebnissen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Ergebnisse' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Krieg',
    translation: 'war; warfare',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Krieg' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Kriegs/Krieges' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Krieg' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Krieg' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Kriege' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Kriege' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Kriegen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Kriege' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Weise',
    translation: 'manner; tune [MUS.]; way - method, manner; fashion; mode; ditty [MUS.]; melody [MUS.]',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Weise' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Weise' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Weise' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Weise' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Weisen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Weisen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Weisen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Weisen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Regierung',
    translation:
      'government; administration (Amer.) [POL.]; regime auch: régime; governance [POL.]; regnancy selten; cabinet',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Regierung' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Regierung' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Regierung' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Regierung' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Regierungen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Regierungen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Regierungen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Regierungen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Stück',
    translation:
      'piece; play - dramatic performance on stage [THEA.]; slice; chunk; lump; cut - of meat; hunk; slips; part; portion; tablet; article; cantle; exemplar',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Stück' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Stücks/Stückes' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Stück' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Stück' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Stücke' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Stücke' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Stücken' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Stücke' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Wohnung',
    translation:
      'apartment (Amer.); dwelling; accommodation; abode [form.] auch [hum.]; home; domicile; habitation; lodging; place of residence; residence; suite; tenement; dwelling place',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Wohnung' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Wohnung' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Wohnung' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Wohnung' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Wohnungen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Wohnungen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Wohnungen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Wohnungen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Gespräch',
    translation:
      'talk; conversation; discussion; call; interview; colloquy; interlocution; dialogue, dialog,dialogue,; chat; convo [ugs.] (kurz für: conversation); complete connection [TELEKOM.]; connection / seltener: connexion, [TELEKOM.]; conversation - in telecommunication [TELEKOM.]',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Gespräch' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Gesprächs/Gespräches' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Gespräch' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Gespräch' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Gespräche' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Gespräche' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Gesprächen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Gespräche' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Meter',
    translation: 'folding rule; folding yardstick',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Meter' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Meters' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Meter' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Meter' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Meter' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Meter' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Metern' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Meter' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Leute',
    translation: 'people plural noun; folk; gentry; peeps plural noun [ugs.]; folks [ugs.]',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Leute' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Leute' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Leuten' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Leute' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Arbeit',
    translation:
      'job; work auch [PHYS.]; labor, labour,; employment; occupation; assignment; activity; task; chore; paper [BILDUNGSW.]; energy [ELEKT.]',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Arbeit' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Arbeit' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Arbeit' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Arbeit' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Arbeiten' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Arbeiten' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Arbeiten' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Arbeiten' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Recht',
    translation:
      'law [JURA]; justice [JURA]; legislation [JURA]; permit; authorization,authorisation, authorization,; privilege [COMP.]; droit [JURA]',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Recht' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Rechts/Rechtes' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Recht' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Recht' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Leben',
    translation: 'life; living; lifetime; existence; animation',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Leben' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Lebens' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Leben' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Leben' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Leben' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Leben' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Leben' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Leben' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Geld',
    translation: 'money; cash - money; chips; funds plural noun [FINAN.]',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Geld' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Gelds/Geldes' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Geld' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Geld' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Gelder' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Gelder' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Geldern' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Gelder' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Wasser',
    translation: 'water',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Wasser' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Wassers' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Wasser' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Wasser' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Wasser' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Wasser' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Wassern' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Wasser' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Sinn',
    translation: 'meaning; mind; signification; tenor; use',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Sinn' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Sinns/Sinnes' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Sinn' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Sinn' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Euro',
    translation: 'euro',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Euro' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Euros/Euro' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Euro' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Euro' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Euros' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Euros' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Euros' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Euros' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Raum',
    translation:
      'room; space auch [AVIAT.][MATH.][TELEKOM.]; region; chamber; range; zone; area; scope; room [fig.]; compartment - of an assembly [TECH.]; volume [TECH.]; district; cave chamber [TECH.]; cave room [TECH.]',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Raum' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Raums/Raumes' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Raum' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Raum' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Räume' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Räume' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Räumen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Räume' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Platz',
    translation:
      'place; room; square; seat; space; spot; site; location; clearance; accommodation; position; public open space; venue; amount of space',
    gender: NounGender.Maskulinum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Platz' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Platzes' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Platz' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Platz' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Plätze' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Plätze' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Plätzen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Plätze' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Eltern',
    translation: 'parents',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Eltern' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Eltern' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Eltern' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Eltern' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Bedeutung',
    translation:
      'meaning; importance; significance; bearing; relevance; sense; heft; import; prominence; consequence - importance; denotation; intent; signification; weight',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Bedeutung' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Bedeutung' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Bedeutung' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Bedeutung' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Bedeutungen' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Bedeutungen' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Bedeutungen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Bedeutungen' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Problem',
    translation:
      'trouble; issue; problem; challenge; hitch; pilikia - Hawaiian for "trouble"; kink; job; headache [fig.]; prob [ugs.] - problem',
    gender: NounGender.Neutrum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Problem' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Problems' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Problem' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Problem' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Probleme' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Probleme' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Problemen' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Probleme' },
    ],
  },
  {
    type: CardType.NOUN,
    value: 'Nacht',
    translation: 'night; nite - simplified spelling of "night" (Amer.) [ugs.]',
    gender: NounGender.Femininum,
    variants: [
      { number: NounNumber.singular, case: Case.Nominativ, value: 'Nacht' },
      { number: NounNumber.singular, case: Case.Genitiv, value: 'Nacht' },
      { number: NounNumber.singular, case: Case.Dativ, value: 'Nacht' },
      { number: NounNumber.singular, case: Case.Akkusativ, value: 'Nacht' },
      { number: NounNumber.plural, case: Case.Nominativ, value: 'Nächte' },
      { number: NounNumber.plural, case: Case.Genitiv, value: 'Nächte' },
      { number: NounNumber.plural, case: Case.Dativ, value: 'Nächten' },
      { number: NounNumber.plural, case: Case.Akkusativ, value: 'Nächte' },
    ],
  },
];
