import type { Phrase } from './types';
import { CardType } from './types';

export const phrases: Phrase[] = [
  {
    type: CardType.PHRASE,
    value: 'Prost',
    translation: 'cheers; to your health',
  },
  {
    type: CardType.PHRASE,
    value: 'Bitte',
    uniqueValue: 'ph-Bitte',
    translation:
      "please; You're welcome!; Not at all.; if you please; Don't mention it!; It's all right!; Never mind!; Pardon?; There you go!; Here you are!;",
  },
  {
    type: CardType.PHRASE,
    value: 'Tschüss/Tschüs',
    uniqueValue: 'Tschüss',
    translation: 'goodbye!; Bye-bye!; Bye!; Cheers!',
  },
  {
    type: CardType.PHRASE,
    value: 'Hallo',
    translation: 'Hello!; Hi!;',
  },
  {
    type: CardType.PHRASE,
    value: 'Danke',
    translation: 'thank you; thanks;',
  },
  {
    type: CardType.PHRASE,
    value: 'Los',
    translation: 'Go! [SPORT.]',
  },
  {
    type: CardType.PHRASE,
    value: 'Schade',
    translation: 'What a pity!; What a shame!; Too bad!;',
  },
  {
    type: CardType.PHRASE,
    value: 'Ach',
    translation: 'Oh!; Ah!; Ouch!;',
  },
  {
    type: CardType.PHRASE,
    value: 'Na',
    translation: 'well; why',
  },
  {
    type: CardType.PHRASE,
    value: 'Achtung',
    uniqueValue: 'ph-Achtung',
    translation: 'Attention!; Heads up!; Look out!; Caution!',
  },
  { type: CardType.PHRASE, mainType: CardType.VERB, value: 'frei haben', translation: 'to have time off' },
  { type: CardType.PHRASE, mainType: CardType.NOUN, value: 'Australien', translation: 'Australia' },
  { type: CardType.PHRASE, mainType: CardType.NOUN, value: 'Malaysia', translation: 'Malaysia' },
  { type: CardType.PHRASE, mainType: CardType.VERB, value: '(sich) sicher sein', translation: 'to be certain' },
  { type: CardType.PHRASE, mainType: CardType.NOUN, value: 'Kanada', translation: 'Canada' },
  { type: CardType.PHRASE, mainType: CardType.NOUN, value: 'Norwegen', translation: 'Norway' },
  { type: CardType.PHRASE, mainType: CardType.NOUN, value: 'England', translation: 'England' },
  { type: CardType.PHRASE, mainType: CardType.NOUN, value: 'Argentinien', translation: 'Argentina' },
  { type: CardType.PHRASE, mainType: CardType.NOUN, value: 'Italien', translation: 'Italy' },
  { type: CardType.PHRASE, mainType: CardType.NOUN, value: 'das 5-Sterne-Hotel', translation: '5-star-hotel' },
  { type: CardType.PHRASE, mainType: CardType.VERB, value: 'Bescheid geben', translation: 'to let (someone) know' },
  { type: CardType.PHRASE, value: 'Sehr geehrte', translation: 'Dear' },
  { type: CardType.PHRASE, mainType: CardType.NOUN, value: 'die 3-Tagekarte', translation: '3 day-ticket' },
  { type: CardType.PHRASE, mainType: CardType.NOUN, value: 'Tschechien', translation: 'Czech Republic' },
  { type: CardType.PHRASE, mainType: CardType.ADJECTIVE, value: 'Tschechisch', translation: 'Czech' },
  { type: CardType.PHRASE, mainType: CardType.NOUN, value: 'Österreich', translation: 'Austria' },
  { type: CardType.PHRASE, mainType: CardType.NOUN, value: 'die Gasteltern', translation: 'host parents' },
  { type: CardType.PHRASE, mainType: CardType.PREPOSITION, value: 'mitten in', translation: 'in the middle of' },
  { type: CardType.PHRASE, value: 'Herzliche Grüße', translation: 'best regards; best wishes' },
  { type: CardType.PHRASE, value: 'danke schön', translation: 'than you very much' },
  { type: CardType.PHRASE, mainType: CardType.VERB, value: 'verfügen über', translation: 'to have' },
  { type: CardType.PHRASE, mainType: CardType.VERB, value: 'spazieren gehen', translation: 'to go for a walk' },
  { type: CardType.PHRASE, mainType: CardType.VERB, value: 'rausbringen', translation: 'to take out' },
  { type: CardType.PHRASE, mainType: CardType.VERB, value: 'mitfeiern', translation: 'to celebrate with someone' },
  { type: CardType.PHRASE, mainType: CardType.VERB, value: 'weitersagen', translation: 'to pass on' },
  { type: CardType.PHRASE, mainType: CardType.NOUN, value: 'die Hochzeitspläne', translation: 'wedding plans' },
  { type: CardType.PHRASE, mainType: CardType.NOUN, value: 'die Treppenreinigung', translation: 'cleaning the stairs' },
  { type: CardType.PHRASE, mainType: CardType.NOUN, value: 'die Hofreinigung', translation: 'yard cleaning' },
  { type: CardType.PHRASE, mainType: CardType.NOUN, value: 'der Essbereich', translation: 'dining area' },
  { type: CardType.PHRASE, mainType: CardType.NOUN, value: 'der Kochbereich', translation: 'cooking area' },
  { type: CardType.PHRASE, mainType: CardType.NOUN, value: 'der Gymnastikkurs', translation: 'gymnastics course' },
  {
    type: CardType.PHRASE,
    mainType: CardType.NOUN,
    value: 'das Mehrgenerationenhaus',
    translation: 'multigenerational house',
  },
  { type: CardType.PHRASE, mainType: CardType.NOUN, value: 'das/der Yoga', translation: 'yoga' },
];
